Info	03/06/24	21:58:00.187	GSEOS	0	1	********************************************************************************
Info	03/06/24	21:58:00.188	GSEOS	0	1	GSEOS 8.1.1491
Info	03/06/24	21:58:00.188	GSEOS	0	1	IMAP
Info	03/06/24	21:58:00.189	GSEOS	0	1	Platform: Windows-10-10.0.19041
Info	03/06/24	21:58:00.189	GSEOS	0	1	Wed Mar  6 21:58:00 2024
Info	03/06/24	21:58:00.190	GSEOS	0	1	********************************************************************************
Info	03/06/24	21:58:00.463	Net	0	1	Server connection: pytest_recv_tlm has been started.
Info	03/06/24	21:58:00.463	Net	0	1	Server connection: pytest_send_tc has been started.
Info	03/06/24	21:58:00.480	Binary Writer	0	1	Binary Writer: "CCSDS_FRAG_TLM" started.
Info	03/06/24	21:58:00.760	Version	0	1	
Info	03/06/24	21:58:00.760	Version	0	1	Version Control Information
Info	03/06/24	21:58:00.760	Version	0	1	----------------------------------------------------------------------
Info	03/06/24	21:58:00.760	Version	0	1	GSEOS:         8.1.1491
Info	03/06/24	21:58:00.760	Version	0	1	Python:        3.7.7 (default, Jun 19 2020, 21:06:32) [MSC v.1900 64 bit (AMD64)]
Info	03/06/24	21:58:00.760	Version	0	1	ExcelLoad:     4.2.042
Info	03/06/24	21:58:00.760	Version	0	1	IMAP - MAG:
Info	03/06/24	21:58:00.760	Version	0	1	
Info	03/06/24	21:58:00.760	Version	0	1	Spreadsheet Version Information
Info	03/06/24	21:58:00.760	Version	0	1	----------------------------------------------------------------------
Info	03/06/24	21:58:00.760	Version	0	1	Instruments\MAG_Common\CMD_MAG.xls (Release: 2023-09-01 Rev: None) converted: Fri Jan 26 13:52:03 2024
Info	03/06/24	21:58:00.760	Version	0	1	Instruments\MAG_Common\TLM_MAG.xls (Release: 2023-09-01 Rev: 1.0) converted: Fri Feb  9 15:19:47 2024
Info	03/06/24	21:58:00.760	Version	0	1	Instruments\MAG_Common\TLM_MAG_SCI.xls (Release: 2023-09-01 Rev: 1.0) converted: Mon Dec 11 14:54:19 2023
Info	03/06/24	21:58:00.760	Version	0	1	Instruments\MAG_Common\TLM_MAG_decoders.xls (Release: 0000-00-00 Rev: 0.0) converted: Fri Feb  9 14:20:08 2024
Info	03/06/24	21:58:00.760	Version	0	1	----------------------------------------------------------------------
Info	03/06/24	21:58:00.760	Version	0	1	
Info	03/06/24	21:58:00.805	IMAP_Bios	0	1	Loading IMAP SCE interface.
Info	03/06/24	21:58:00.805	Message	0	1	Setting Message Filter: Error reading from pipeOut:*, ERROR, OKBios, 0.
Info	03/06/24	21:58:00.842	OKBios	0	1	Initializing device: XEM1
Info	03/06/24	21:58:00.842	OKBios	0	1	Entering device service thread for device: XEM1.
Info	03/06/24	21:58:00.877	OKBios	0	1	Device ID: Opal Kelly XEM6010.
Info	03/06/24	21:58:00.877	OKBios	0	1	Device serial number: 2019000T3G.
Info	03/06/24	21:58:00.877	OKBios	0	1	Device board model: XEM6010-LX45.
Info	03/06/24	21:58:00.877	OKBios	0	1	Setting transfer size to: 2 bytes.
Info	03/06/24	21:58:00.877	OKBios	0	1	Device: XEM1 (Opal Kelly XEM6010) configured. No bit file loaded.
Info	03/06/24	21:58:03.079	IMAP_Bios	0	1	SCE detected to be not running. Reset SCE.
Info	03/06/24	21:58:03.079	IMAP_Bios	0	1	Resetting FPGA with bitfile: SCE/IMAP_SCE_XEM_6010_026.bit...
Info	03/06/24	21:58:03.246	OKBios	0	1	Device: XEM1 (Opal Kelly XEM6010) configured using bit file: SCE/IMAP_SCE_XEM_6010_026.bit.
Info	03/06/24	21:58:03.302	OKBios	0	1	Connection to Opal Kelly device established.
Info	03/06/24	21:58:03.447	IMAP_Bios	0	1	Setting SCE FPGA start bit
Info	03/06/24	21:58:03.763	IMAP_Bios	0	1	Configuring SCE:
Info	03/06/24	21:58:03.763	IMAP_Bios	0	1	Configuring TLM UART: (115200, o, 1).
Info	03/06/24	21:58:03.763	IMAP_Bios	0	1	Configuring CMD UART: (115200, o, 1).
Info	03/06/24	21:58:03.763	IMAP_Bios	0	1	Configuring minor frame count: 50.
Info	03/06/24	21:58:03.763	IMAP_Bios	0	1	Configuring minor frame time: 20 ms.
Info	03/06/24	21:58:03.763	IMAP_Bios	0	1	Configuring analog update time: 1000 ms.
Info	03/06/24	21:58:03.765	IMAP_Bios	0	1	Configuring CMD 1PPS dead time: 150000 us.
Info	03/06/24	21:58:03.765	IMAP_Bios	0	1	Configuring TLM 1PPS dead time: 11000 us.
Info	03/06/24	21:58:03.765	IMAP_Bios	0	1	Configuring instrument voltage limits: 0.00 .. 33.00 V.
Info	03/06/24	21:58:03.765	IMAP_Bios	0	1	Configuring instrument current limits: 0.000 .. 2.000 A.
Info	03/06/24	21:58:03.765	IMAP_Bios	0	1	Configuring aux voltage limits: 0.00 .. 33.00 V.
Info	03/06/24	21:58:03.765	IMAP_Bios	0	1	Configuring aux current limits: 0.000 .. 2.000 A.
Info	03/06/24	21:58:03.765	IMAP_Bios	0	1	SCE configuration completed.
Info	03/06/24	21:58:03.765	Message	0	1	Removing Message Filter: Error reading from pipeOut:*, ERROR, OKBios, 0.
Warn	03/06/24	21:58:03.825	User	0	1	config: Instrument Sys Path not configured
Info	03/06/24	21:58:03.825	User	0	1	config: Initializing Command Logger
Info	03/06/24	21:58:03.892	User	0	1	config:CommandLogger - Ignoring commands matching regex: 'xxx'
Warn	03/06/24	21:58:03.892	User	0	1	config: Telemetry Monitor not configured
Warn	03/06/24	21:58:03.892	User	0	1	config: Memory Dump Monitor not configured
Warn	03/06/24	21:58:03.892	User	0	1	config: Alarm Monitor not configured
Warn	03/06/24	21:58:03.894	User	0	1	config: UDP Exploder not configured
Info	03/06/24	21:58:03.894	User	0	1	config: Initializing CCSDS Dispatcher
Info	03/06/24	21:58:03.915	User	0	1	config:ccsds_dispatch - APID 0x431 -> MAG_EHS_ERRDATA
Info	03/06/24	21:58:03.915	User	0	1	config:ccsds_dispatch - APID 0x401 -> MAG_EHS_BSW
Info	03/06/24	21:58:03.915	User	0	1	config:ccsds_dispatch - APID 0x425 -> MAG_ELS_ITF
Info	03/06/24	21:58:03.915	User	0	1	config:ccsds_dispatch - APID 0x40e -> MAG_MEM_MRAMTSEGREP
Info	03/06/24	21:58:03.915	User	0	1	config:ccsds_dispatch - APID 0x433 -> MAG_TCC_FEEFAIL
Info	03/06/24	21:58:03.915	User	0	1	config:ccsds_dispatch - APID 0x435 -> MAG_TCC_PARAMFAIL
Info	03/06/24	21:58:03.915	User	0	1	config:ccsds_dispatch - APID 0x436 -> MAG_TCC_FILEFAIL
Info	03/06/24	21:58:03.915	User	0	1	config:ccsds_dispatch - APID 0x415 -> MAG_HSK_SID20
Info	03/06/24	21:58:03.915	User	0	1	config:ccsds_dispatch - APID 0x3e3 -> MAG_PROG_NOOP
Info	03/06/24	21:58:03.915	User	0	1	config:ccsds_dispatch - APID 0x406 -> MAG_PROG_BTSUCC
Info	03/06/24	21:58:03.915	User	0	1	config:ccsds_dispatch - APID 0x405 -> MAG_PROG_BTSUCC
Info	03/06/24	21:58:03.915	User	0	1	config:ccsds_dispatch - APID 0x400 -> MAG_PROG_MTRAN
Info	03/06/24	21:58:03.915	User	0	1	config:ccsds_dispatch - APID 0x422 -> MAG_TCA_SUCC
Info	03/06/24	21:58:03.915	User	0	1	config:ccsds_dispatch - APID 0x423 -> MAG_TCC_SUCC
Info	03/06/24	21:58:03.915	User	0	1	config:ccsds_dispatch - APID 0x404 -> MAG_HSK_SID1
Info	03/06/24	21:58:03.915	User	0	1	config:ccsds_dispatch - APID 0x41f -> MAG_HSK_SID2
Info	03/06/24	21:58:03.915	User	0	1	config:ccsds_dispatch - APID 0x427 -> MAG_HSK_PW
Info	03/06/24	21:58:03.915	User	0	1	config:ccsds_dispatch - APID 0x428 -> MAG_HSK_STATUS
Info	03/06/24	21:58:03.915	User	0	1	config:ccsds_dispatch - APID 0x41b -> MAG_HSK_PROCSTAT
Info	03/06/24	21:58:03.915	User	0	1	config:ccsds_dispatch - APID 0x43b -> MAG_HSK_SCI
Info	03/06/24	21:58:03.915	User	0	1	config:ccsds_dispatch - APID 0x41d -> MAG_HSK_SID15
Info	03/06/24	21:58:03.915	User	0	1	config:ccsds_dispatch - APID 0x424 -> MAG_HSK_SID12
Info	03/06/24	21:58:03.915	User	0	1	config:ccsds_dispatch - APID 0x41e -> MAG_HSK_SID16
Info	03/06/24	21:58:03.915	User	0	1	config:ccsds_dispatch - APID 0x3e9 -> MAG_SCI_IALIRT
Info	03/06/24	21:58:03.915	User	0	1	config:ccsds_dispatch - APID 0x3fc -> MAG_SCI_IALIRT
Info	03/06/24	21:58:03.915	User	0	1	config:ccsds_dispatch - APID 0x40c -> MAG_SCI_1920
Info	03/06/24	21:58:03.915	User	0	1	config:ccsds_dispatch - APID 0x41c -> MAG_SCI_NORM
Info	03/06/24	21:58:03.915	User	0	1	config:ccsds_dispatch - APID 0x42c -> MAG_SCI_BURST
Info	03/06/24	21:58:03.915	User	0	1	config:ccsds_dispatch - APID 0x409 -> MAG_MEM_CHCKREP
Info	03/06/24	21:58:03.915	User	0	1	config:ccsds_dispatch - APID 0x3fa -> MAG_MEM_DMP
Info	03/06/24	21:58:03.915	User	0	1	config:ccsds_dispatch - APID 0x40d -> MAG_HSK_HKADCPRMLIM
Info	03/06/24	21:58:03.915	User	0	1	config:ccsds_dispatch - APID 0x3e8 -> MAG_HSK_AUTONOMY
Info	03/06/24	21:58:03.915	User	0	1	config:ccsds_dispatch - APID 0x426 -> MAG_TCA_INVCCSDS
Info	03/06/24	21:58:03.915	User	0	1	config:ccsds_dispatch - APID 0x429 -> MAG_TCC_FAIL
Info	03/06/24	21:58:03.915	User	0	1	config:ccsds_dispatch - APID 0x42a -> MAG_TCC_FAILMEM
Info	03/06/24	21:58:03.915	User	0	1	config:ccsds_dispatch - APID 0x42b -> MAG_EHS_SWTRAP
Info	03/06/24	21:58:03.915	User	0	1	config:ccsds_dispatch - APID 0x42d -> MAG_TCC_SPIERR
Info	03/06/24	21:58:03.915	User	0	1	config:ccsds_dispatch - APID 0x42f -> MAG_EHS_AUTONOMY
Info	03/06/24	21:58:03.915	User	0	1	config:ccsds_dispatch - APID 0x430 -> MAG_EHS_GENEVNT
Info	03/06/24	21:58:03.915	User	0	1	config:ccsds_dispatch - APID 0x42e -> MAG_EHS_HKADC
Info	03/06/24	21:58:03.915	User	0	1	config:ccsds_dispatch - APID 0x402 -> MAG_EHS_SWPCKDROP
Info	03/06/24	21:58:03.915	User	0	1	config:ccsds_dispatch - APID 0x40a -> MAG_EHS_CRSHREP
Info	03/06/24	21:58:03.915	User	0	1	config:ccsds_dispatch - APID 0x439 -> MAG_ELS_CONFLD
Info	03/06/24	21:58:03.915	User	0	1	config:ccsds_dispatch - APID 0x438 -> MAG_EHS_FEE
Info	03/06/24	21:58:03.915	User	0	1	config:ccsds_dispatch - APID 0x437 -> MAG_EHS_BUFF
Info	03/06/24	21:58:03.915	User	0	1	config:ccsds_dispatch - APID 0x432 -> MAG_EHS_SEMAPH
Info	03/06/24	21:58:03.915	User	0	1	config:ccsds_dispatch - APID 0x3fe -> MAG_EHS_OSERR
Info	03/06/24	21:58:03.915	User	0	1	config:ccsds_dispatch - APID 0x434 -> MAG_TCC_OSFAIL
Warn	03/06/24	21:58:03.915	User	0	1	config: Telemetry Watchdog not configured
Warn	03/06/24	21:58:03.915	User	0	1	config: Binary Log not configured
Info	03/06/24	21:58:03.915	User	0	1	config: Initializing CSV Exports
Info	03/06/24	21:58:03.944	User	0	1	config:csvlog - export_sidone
Info	03/06/24	21:58:03.946	User	0	1	config:csvlog - export_conf
Info	03/06/24	21:58:03.950	User	0	1	config:csvlog - export_sidtwo
Info	03/06/24	21:58:03.950	User	0	1	config:csvlog - export_data
Info	03/06/24	21:58:03.950	User	0	1	config:csvlog - export_pwr
Info	03/06/24	21:58:03.950	User	0	1	config:csvlog - export_stat
Info	03/06/24	21:58:03.950	User	0	1	config:csvlog - export_proc
Info	03/06/24	21:58:03.950	User	0	1	config:csvlog - export_mem
Info	03/06/24	21:58:03.950	User	0	1	config:csvlog - export_hkadc
Info	03/06/24	21:58:03.950	User	0	1	config:csvlog - export_ialirt
Warn	03/06/24	21:58:03.951	User	0	1	config: Test Core not configured
Warn	03/06/24	21:58:03.951	User	0	1	config: Recorder not configured
Warn	03/06/24	21:58:03.951	User	0	1	config: RS232 BIOS not configured
Info	03/06/24	21:58:09.834	Sequencer	0	1	Sequencer 'Check Time & Status Customization File Existence' started.
Info	03/06/24	21:58:10.194	SCE	0	1	SPP SCE UART Vers 026
Info	03/06/24	21:58:10.196	IMAP_Bios	0	1	Starting TLM data acquisition.
Info	03/06/24	21:58:10.282	SCE	0	1	tlm baud=115200 par=O stop=1
Info	03/06/24	21:58:10.282	SCE	0	1	cmd baud=115200 par=O stop=1
Info	03/06/24	21:58:10.282	SCE	0	1	Minor Frame Count set to 50
Info	03/06/24	21:58:10.282	SCE	0	1	Minor Frame Time set to 20
Info	03/06/24	21:58:10.282	SCE	0	1	Analog Update rate set to 1000 ms
Info	03/06/24	21:58:11.355	SCE	0	1	Acquisition started
Info	03/06/24	22:00:58.653	CSTOL	0	1	@PW  Starting procedure $RCSfile: mag_cpt.prc,v $
Info	03/06/24	22:00:58.665	CSTOL	0	1	@PW  $Revision: 1.0 $
Info	03/06/24	22:00:58.687	CSTOL	0	1	@PW  This CPT assumes:
Info	03/06/24	22:00:58.698	CSTOL	0	1	@PW  BSW:   v2.04
Info	03/06/24	22:00:58.716	CSTOL	0	1	@PW  ASW:   v3.01+
Info	03/06/24	22:00:58.726	CSTOL	0	1	@PW  GSE:   v15.1
Info	03/06/24	22:00:58.739	CSTOL	0	1	@PW  GSEOS: IMAP.7.3.029
Info	03/06/24	22:00:59.424	CSTOL	0	1	@PW  Starting procedure $RCSfile: mag_pwr_on.prc,v $
Info	03/06/24	22:00:59.437	CSTOL	0	1	@PW  $Revision: 1.0 $
Info	03/06/24	22:00:59.459	CSTOL	0	1	@PW  Verify with instrument team that they are GO to power on.
Info	03/06/24	22:00:59.470	CSTOL	0	1	@PW  Call out to FC to power on MAG.
Info	03/06/24	22:01:29.947	CSTOL	0	1	@PW  FC confirmed that MAG is powered.
Info	03/06/24	22:01:30.032	CSTOL	0	1	@PW  Waiting for BSW boot event...
Info	03/06/24	22:01:30.105	CSTOL	0	1	@PW  Boot packet received. Proceeding to verification.
Info	03/06/24	22:01:30.138	CSTOL	0	1	@PW  Sending NOOP to stay in BSW...
Info	03/06/24	22:01:30.210	CSTOL	0	1	@PW  BSW boot event successfully received.
Info	03/06/24	22:01:30.220	CSTOL	0	1	@PW  Boot EVENT_ID = bswBootSuccess
Info	03/06/24	22:01:30.299	CSTOL	0	1	MAG_PROG_BTSUCC PROM_CSUM = 35732. DN
Info	03/06/24	22:01:30.311	CSTOL	0	1	@PW  Expected checksum is 35732. DN
Info	03/06/24	22:01:30.372	CSTOL	0	1	@PW  Checksum has been verified.
Info	03/06/24	22:01:30.414	CSTOL	0	1	MAG_PROG_BTSUCC EVENT_ID = bswBootSuccess
Info	03/06/24	22:01:30.426	CSTOL	0	1	MAG_PROG_BTSUCC SW_VERNUM = 204. DN
Info	03/06/24	22:01:30.437	CSTOL	0	1	MAG_PROG_BTSUCC PROM_CSUM = 35732. DN
Info	03/06/24	22:01:30.448	CSTOL	0	1	MAG_PROG_BTSUCC HW_MODEL = FM
Info	03/06/24	22:01:30.486	CSTOL	0	1	@PW  End of MAG Power On Script.
Info	03/06/24	22:01:30.496	CSTOL	0	1	@PW  Finishing $RCSfile: mag_pwr_on.prc,v $
Info	03/06/24	22:01:31.131	CSTOL	0	1	@PW  Starting procedure $RCSfile: mag_check_hk.prc,v $
Info	03/06/24	22:01:31.151	CSTOL	0	1	@PW  $Revision: 1.0 $
Info	03/06/24	22:01:31.266	CSTOL	0	1	@PW  Requesting MAG Power HK packet...
Info	03/06/24	22:01:35.351	CSTOL	0	1	@PW  MAG Power HK Report received. Proceeding to verification.
Info	03/06/24	22:01:39.344	CSTOL	0	1	@PW  Status packet received. Proceeding to verification.
Info	03/06/24	22:01:39.654	CSTOL	0	1	MAG_HSK_PW P1V5V = 1.52370834 V
Info	03/06/24	22:01:39.665	CSTOL	0	1	MAG_HSK_PW P1V8V = 1.82973516 V
Info	03/06/24	22:01:39.683	CSTOL	0	1	MAG_HSK_PW P2V5V = 2.54942028 V
Info	03/06/24	22:01:39.694	CSTOL	0	1	MAG_HSK_PW P3V3V = 3.365204948 V
Info	03/06/24	22:01:39.706	CSTOL	0	1	MAG_HSK_PW P8V = 9.733416298 V
Info	03/06/24	22:01:39.717	CSTOL	0	1	MAG_HSK_PW N8V = -9.721585082 V
Info	03/06/24	22:01:39.729	CSTOL	0	1	MAG_HSK_PW P2V4V = 2.364140868 V
Info	03/06/24	22:01:39.746	CSTOL	0	1	MAG_HSK_PW P1V5I = 424.4744135 mA
Info	03/06/24	22:01:39.756	CSTOL	0	1	MAG_HSK_PW P1V8I = 18.43602852 mA
Info	03/06/24	22:01:39.767	CSTOL	0	1	MAG_HSK_PW P2V5I = 86.62146875 mA
Info	03/06/24	22:01:39.778	CSTOL	0	1	MAG_HSK_PW P3V3I = 116.3256726 mA
Info	03/06/24	22:01:39.789	CSTOL	0	1	MAG_HSK_PW P8VI = 119.7507 mA
Info	03/06/24	22:01:39.806	CSTOL	0	1	MAG_HSK_PW N8VI = 90.3258 mA
Info	03/06/24	22:01:39.819	CSTOL	0	1	MAG_HSK_PW ICU_TEMP = 21.0765987 C
Info	03/06/24	22:01:39.829	CSTOL	0	1	MAG_HSK_PW FOB_TEMP = 24.05717231 C
Info	03/06/24	22:01:39.841	CSTOL	0	1	MAG_HSK_PW FIB_TEMP = 24.13835464 C
Info	03/06/24	22:01:39.851	CSTOL	0	1	MAG_HSK_STATUS MAGMODE = Standby
Info	03/06/24	22:01:39.900	CSTOL	0	1	@PW  MAG Power HK parameters within limits. Not in SAFE.
Info	03/06/24	22:01:40.036	CSTOL	0	1	@PW  Transitioning to ASW in MRAMSLOT2 ...
Info	03/06/24	22:01:40.657	CSTOL	0	1	@PW  Starting procedure $RCSfile: mag_transition.prc,v $
Info	03/06/24	22:01:40.667	CSTOL	0	1	@PW  $Revision: 1.0 $
Info	03/06/24	22:01:40.749	CSTOL	0	1	@PW  Waiting 3 seconds to allow user to abort...
Info	03/06/24	22:01:43.851	CSTOL	0	1	@PW  Waiting for boot event packet...
Error	03/06/24	22:01:51.315	ITF_TLM_RATE Decoder	0	1	No ITF for regular VC: 11 present in 1PPS for major frame: 218
Error	03/06/24	22:01:51.315	ITF_TLM Decoder	0	1	Wrong sequence counter for VC: 11. Expected: 26, received: 0
Info	03/06/24	22:01:51.375	CSTOL	0	1	@PW  ASW boot packet received. Proceeding to verification.
Info	03/06/24	22:01:51.546	CSTOL	0	1	MAG_PROG_BTSUCC EVENT_ID = aswBootSuccess
Info	03/06/24	22:01:51.559	CSTOL	0	1	MAG_PROG_BTSUCC PHAPID = 1030. DN
Info	03/06/24	22:01:51.575	CSTOL	0	1	MAG_PROG_BTSUCC SW_VERNUM = 301. DN
Info	03/06/24	22:01:51.585	CSTOL	0	1	MAG_PROG_MTRAN EVENT_ID = modeTransition
Info	03/06/24	22:01:51.596	CSTOL	0	1	MAG_PROG_MTRAN PREVM_ID = Standby
Info	03/06/24	22:01:51.608	CSTOL	0	1	MAG_PROG_MTRAN CURRM_ID = Config
Info	03/06/24	22:01:51.644	CSTOL	0	1	@PW  Successfully transitioned to ASW.
Info	03/06/24	22:01:52.359	CSTOL	0	1	@PW  Starting procedure $RCSfile: mag_noop.prc,v $
Info	03/06/24	22:01:52.371	CSTOL	0	1	@PW  $Revision: 1.0 $
Info	03/06/24	22:01:52.460	CSTOL	0	1	@PW  Sending NOOP connection test...
Info	03/06/24	22:01:56.615	CSTOL	0	1	@PW  Connection test response report received. Proceeding to verification.
Info	03/06/24	22:01:56.750	CSTOL	0	1	MAG_PROG_NOOP PUS_STYPE = 17. DN
Info	03/06/24	22:01:56.762	CSTOL	0	1	MAG_PROG_NOOP PUS_SSUBTYPE = 2. DN
Info	03/06/24	22:01:56.792	CSTOL	0	1	@PW  Connection verified.
Info	03/06/24	22:01:57.457	CSTOL	0	1	@PW  Starting procedure $RCSfile: mag_check_hk.prc,v $
Info	03/06/24	22:01:57.469	CSTOL	0	1	@PW  $Revision: 1.0 $
Info	03/06/24	22:01:57.589	CSTOL	0	1	@PW  Requesting MAG Power HK packet...
Info	03/06/24	22:02:01.348	CSTOL	0	1	@PW  MAG Power HK Report received. Proceeding to verification.
Info	03/06/24	22:02:05.339	CSTOL	0	1	@PW  Status packet received. Proceeding to verification.
Info	03/06/24	22:02:05.631	CSTOL	0	1	MAG_HSK_PW P1V5V = 1.52370834 V
Info	03/06/24	22:02:05.641	CSTOL	0	1	MAG_HSK_PW P1V8V = 1.83053838 V
Info	03/06/24	22:02:05.654	CSTOL	0	1	MAG_HSK_PW P2V5V = 2.54942028 V
Info	03/06/24	22:02:05.664	CSTOL	0	1	MAG_HSK_PW P3V3V = 3.365204948 V
Info	03/06/24	22:02:05.683	CSTOL	0	1	MAG_HSK_PW P8V = 9.730839957 V
Info	03/06/24	22:02:05.694	CSTOL	0	1	MAG_HSK_PW N8V = -9.721585082 V
Info	03/06/24	22:02:05.706	CSTOL	0	1	MAG_HSK_PW P2V4V = 2.359484756 V
Info	03/06/24	22:02:05.717	CSTOL	0	1	MAG_HSK_PW P1V5I = 433.3115054 mA
Info	03/06/24	22:02:05.729	CSTOL	0	1	MAG_HSK_PW P1V8I = 18.27692779 mA
Info	03/06/24	22:02:05.744	CSTOL	0	1	MAG_HSK_PW P2V5I = 86.51600394 mA
Info	03/06/24	22:02:05.756	CSTOL	0	1	MAG_HSK_PW P3V3I = 115.9274475 mA
Info	03/06/24	22:02:05.767	CSTOL	0	1	MAG_HSK_PW P8VI = 119.6314 mA
Info	03/06/24	22:02:05.778	CSTOL	0	1	MAG_HSK_PW N8VI = 90.3258 mA
Info	03/06/24	22:02:05.789	CSTOL	0	1	MAG_HSK_PW ICU_TEMP = 21.3237441 C
Info	03/06/24	22:02:05.809	CSTOL	0	1	MAG_HSK_PW FOB_TEMP = 24.05717231 C
Info	03/06/24	22:02:05.819	CSTOL	0	1	MAG_HSK_PW FIB_TEMP = 24.13835464 C
Info	03/06/24	22:02:05.831	CSTOL	0	1	MAG_HSK_STATUS MAGMODE = Config
Info	03/06/24	22:02:05.881	CSTOL	0	1	@PW  MAG Power HK parameters within limits. Not in SAFE.
Info	03/06/24	22:02:06.625	CSTOL	0	1	@PW  Starting procedure $RCSfile: mag_config_hk.prc,v $
Info	03/06/24	22:02:06.644	CSTOL	0	1	@PW  $Revision: 1.0 $
Info	03/06/24	22:02:06.667	CSTOL	0	1	@PW  Configuring the HK and resetting error lights...
Info	03/06/24	22:02:10.332	CSTOL	0	1	@PW  MAG HK Status interval set to 20 seconds.
Info	03/06/24	22:02:14.345	CSTOL	0	1	@PW  MAG HK Processor Status interval set to 3600 seconds.
Info	03/06/24	22:02:18.338	CSTOL	0	1	@PW  MAG HK SID15 interval set to 3600 seconds.
Info	03/06/24	22:02:22.357	CSTOL	0	1	@PW  MAG HK SID16 interval set to 3600 seconds.
Info	03/06/24	22:02:26.322	CSTOL	0	1	@PW  MAG enable SID16 command complete
Info	03/06/24	22:02:30.417	CSTOL	0	1	@PW  SID16 received
Info	03/06/24	22:02:31.150	CSTOL	0	1	@PW  Starting procedure $RCSfile: mag_activate.prc,v $
Info	03/06/24	22:02:31.160	CSTOL	0	1	@PW  $Revision: 1.0 $
Info	03/06/24	22:02:31.246	CSTOL	0	1	@PW  Activating FOB with delay, and monitoring...
Info	03/06/24	22:02:34.305	CSTOL	0	1	@PW  User has sent command to activate FOB...
Info	03/06/24	22:03:12.338	CSTOL	0	1	@PW  FOB activation command completion event received. Proceeding to verification.
Info	03/06/24	22:03:12.469	CSTOL	0	1	@PW  Command to activate FOB is accepted and completed.
Info	03/06/24	22:03:13.117	CSTOL	0	1	@PW  Starting procedure $RCSfile: mag_check_hk.prc,v $
Info	03/06/24	22:03:13.128	CSTOL	0	1	@PW  $Revision: 1.0 $
Info	03/06/24	22:03:13.253	CSTOL	0	1	@PW  Requesting MAG Power HK packet...
Info	03/06/24	22:03:16.342	CSTOL	0	1	@PW  MAG Power HK Report received. Proceeding to verification.
Info	03/06/24	22:03:20.367	CSTOL	0	1	@PW  Status packet received. Proceeding to verification.
Info	03/06/24	22:03:20.647	CSTOL	0	1	MAG_HSK_PW P1V5V = 1.52370834 V
Info	03/06/24	22:03:20.658	CSTOL	0	1	MAG_HSK_PW P1V8V = 1.83053838 V
Info	03/06/24	22:03:20.668	CSTOL	0	1	MAG_HSK_PW P2V5V = 2.54942028 V
Info	03/06/24	22:03:20.681	CSTOL	0	1	MAG_HSK_PW P3V3V = 3.365204948 V
Info	03/06/24	22:03:20.698	CSTOL	0	1	MAG_HSK_PW P8V = 9.653549727 V
Info	03/06/24	22:03:20.710	CSTOL	0	1	MAG_HSK_PW N8V = -9.646444898 V
Info	03/06/24	22:03:20.721	CSTOL	0	1	MAG_HSK_PW P2V4V = 2.358320728 V
Info	03/06/24	22:03:20.733	CSTOL	0	1	MAG_HSK_PW P1V5I = 431.6396231 mA
Info	03/06/24	22:03:20.744	CSTOL	0	1	MAG_HSK_PW P1V8I = 20.58388826 mA
Info	03/06/24	22:03:20.760	CSTOL	0	1	MAG_HSK_PW P2V5I = 90.3127371 mA
Info	03/06/24	22:03:20.772	CSTOL	0	1	MAG_HSK_PW P3V3I = 116.8831878 mA
Info	03/06/24	22:03:20.782	CSTOL	0	1	MAG_HSK_PW P8VI = 155.0635 mA
Info	03/06/24	22:03:20.793	CSTOL	0	1	MAG_HSK_PW N8VI = 120.836 mA
Info	03/06/24	22:03:20.805	CSTOL	0	1	MAG_HSK_PW ICU_TEMP = 21.6944622 C
Info	03/06/24	22:03:20.823	CSTOL	0	1	MAG_HSK_PW FOB_TEMP = 24.05717231 C
Info	03/06/24	22:03:20.835	CSTOL	0	1	MAG_HSK_PW FIB_TEMP = 24.01458488 C
Info	03/06/24	22:03:20.845	CSTOL	0	1	MAG_HSK_STATUS MAGMODE = Config
Info	03/06/24	22:03:20.898	CSTOL	0	1	@PW  MAG Power HK parameters within limits. Not in SAFE.
Info	03/06/24	22:03:21.526	CSTOL	0	1	@PW  Starting procedure $RCSfile: mag_activate.prc,v $
Info	03/06/24	22:03:21.539	CSTOL	0	1	@PW  $Revision: 1.0 $
Info	03/06/24	22:03:21.621	CSTOL	0	1	@PW  Activating FIB with delay, and monitoring...
Info	03/06/24	22:03:25.030	CSTOL	0	1	@PW  User has sent command to activate FIB...
Info	03/06/24	22:04:04.369	CSTOL	0	1	@PW  FIB activation command completion event received. Proceeding to verification.
Info	03/06/24	22:04:04.519	CSTOL	0	1	@PW  Command to activate FIB is accepted and completed.
Info	03/06/24	22:04:05.167	CSTOL	0	1	@PW  Starting procedure $RCSfile: mag_check_hk.prc,v $
Info	03/06/24	22:04:05.177	CSTOL	0	1	@PW  $Revision: 1.0 $
Info	03/06/24	22:04:05.306	CSTOL	0	1	@PW  Requesting MAG Power HK packet...
Info	03/06/24	22:04:09.325	CSTOL	0	1	@PW  MAG Power HK Report received. Proceeding to verification.
Info	03/06/24	22:04:12.367	CSTOL	0	1	@PW  Status packet received. Proceeding to verification.
Info	03/06/24	22:04:12.667	CSTOL	0	1	MAG_HSK_PW P1V5V = 1.52370834 V
Info	03/06/24	22:04:12.681	CSTOL	0	1	MAG_HSK_PW P1V8V = 1.82973516 V
Info	03/06/24	22:04:12.697	CSTOL	0	1	MAG_HSK_PW P2V5V = 2.54942028 V
Info	03/06/24	22:04:12.709	CSTOL	0	1	MAG_HSK_PW P3V3V = 3.365204948 V
Info	03/06/24	22:04:12.720	CSTOL	0	1	MAG_HSK_PW P8V = 9.578835838 V
Info	03/06/24	22:04:12.732	CSTOL	0	1	MAG_HSK_PW N8V = -9.571304715 V
Info	03/06/24	22:04:12.743	CSTOL	0	1	MAG_HSK_PW P2V4V = 2.3571567 V
Info	03/06/24	22:04:12.762	CSTOL	0	1	MAG_HSK_PW P1V5I = 431.4007828 mA
Info	03/06/24	22:04:12.773	CSTOL	0	1	MAG_HSK_PW P1V8I = 22.73174801 mA
Info	03/06/24	22:04:12.785	CSTOL	0	1	MAG_HSK_PW P2V5I = 94.21493507 mA
Info	03/06/24	22:04:12.796	CSTOL	0	1	MAG_HSK_PW P3V3I = 117.679638 mA
Info	03/06/24	22:04:12.808	CSTOL	0	1	MAG_HSK_PW P8VI = 192.4044 mA
Info	03/06/24	22:04:12.825	CSTOL	0	1	MAG_HSK_PW N8VI = 153.3488 mA
Info	03/06/24	22:04:12.835	CSTOL	0	1	MAG_HSK_PW ICU_TEMP = 21.8180349 C
Info	03/06/24	22:04:12.849	CSTOL	0	1	MAG_HSK_PW FOB_TEMP = 24.05717231 C
Info	03/06/24	22:04:12.859	CSTOL	0	1	MAG_HSK_PW FIB_TEMP = 23.89088338 C
Info	03/06/24	22:04:12.871	CSTOL	0	1	MAG_HSK_STATUS MAGMODE = Config
Info	03/06/24	22:04:12.917	CSTOL	0	1	@PW  MAG Power HK parameters within limits. Not in SAFE.
Info	03/06/24	22:04:13.127	CSTOL	0	1	MAG_HSK_PW MAGOSATFLAGX = NotSaturated
Info	03/06/24	22:04:13.138	CSTOL	0	1	MAG_HSK_PW MAGOSATFLAGY = NotSaturated
Info	03/06/24	22:04:13.148	CSTOL	0	1	MAG_HSK_PW MAGOSATFLAGZ = NotSaturated
Info	03/06/24	22:04:13.161	CSTOL	0	1	MAG_HSK_PW MAGISATFLAGX = NotSaturated
Info	03/06/24	22:04:13.174	CSTOL	0	1	MAG_HSK_PW MAGISATFLAGY = NotSaturated
Info	03/06/24	22:04:13.184	CSTOL	0	1	MAG_HSK_PW MAGISATFLAGZ = NotSaturated
Info	03/06/24	22:04:13.198	CSTOL	0	1	MAG_HSK_STATUS FOBSTAT = Active
Info	03/06/24	22:04:13.210	CSTOL	0	1	MAG_HSK_STATUS FIBSTAT = Active
Info	03/06/24	22:04:13.220	CSTOL	0	1	MAG_HSK_PW P8VI = 192.4044 mA
Info	03/06/24	22:04:13.233	CSTOL	0	1	MAG_HSK_PW N8VI = 153.3488 mA
Info	03/06/24	22:04:13.279	CSTOL	0	1	@PW  MAG HK nominal post FEE activation.
Info	03/06/24	22:04:13.312	CSTOL	0	1	@PW  FC call out to MAG team to confirm sensors have correctly fired.
Info	03/06/24	22:04:38.664	CSTOL	0	1	@PW  User has confirmed MAG HK looks nominal and has continued.
Info	03/06/24	22:04:38.767	CSTOL	0	1	@PW  Sending command to go to Burst 128-128 mode...
Info	03/06/24	22:04:39.480	CSTOL	0	1	@PW  Starting procedure $RCSfile: mag_science.prc,v $
Info	03/06/24	22:04:39.492	CSTOL	0	1	@PW  $Revision: 1.0 $
Info	03/06/24	22:04:43.319	CSTOL	0	1	@PW Burst Mode transition event received. Proceeding to verification.
Info	03/06/24	22:04:43.364	CSTOL	0	1	MAG_PROG_MTRAN EVENT_ID = modeTransition
Info	03/06/24	22:04:43.375	CSTOL	0	1	MAG_PROG_MTRAN PREVM_ID = Config
Info	03/06/24	22:04:43.384	CSTOL	0	1	MAG_PROG_MTRAN CURRM_ID = Burst
Info	03/06/24	22:04:43.426	CSTOL	0	1	@PW  MAG successfully changed mode to Burst
Info	03/06/24	22:04:44.339	CSTOL	0	1	@PW  Starting procedure $RCSfile: mag_config_FEE.prc,v $
Info	03/06/24	22:04:44.352	CSTOL	0	1	@PW  $Revision: 1.0 $
Info	03/06/24	22:04:44.414	CSTOL	0	1	@PW  Configuring FOB...
Info	03/06/24	22:04:44.426	CSTOL	0	1	@PW  Setting FOB delay value to 3...
Info	03/06/24	22:04:48.325	CSTOL	0	1	@PW FOB set delay command completed.
Info	03/06/24	22:04:48.375	CSTOL	0	1	@PW  Enabling FEE autorange for FOB with 50 second delay...
Info	03/06/24	22:04:52.331	CSTOL	0	1	@PW  Enable FOB FEE autorange command completed.
Info	03/06/24	22:04:52.365	CSTOL	0	1	@PW  Enabling ICU autorange for FOB with delay count 38400...
Info	03/06/24	22:04:56.325	CSTOL	0	1	@PW  Enable FOB ICU autorange command completed.
Info	03/06/24	22:04:57.025	CSTOL	0	1	@PW  Starting procedure $RCSfile: mag_config_FEE.prc,v $
Info	03/06/24	22:04:57.040	CSTOL	0	1	@PW  $Revision: 1.0 $
Info	03/06/24	22:04:57.118	CSTOL	0	1	@PW  Configuring FIB...
Info	03/06/24	22:04:57.130	CSTOL	0	1	@PW  Setting FIB delay value to 3...
Info	03/06/24	22:05:00.325	CSTOL	0	1	@PW FIB set delay command completed.
Info	03/06/24	22:05:00.368	CSTOL	0	1	@PW  Enabling FEE autorange for FIB with 50 second delay...
Info	03/06/24	22:05:04.332	CSTOL	0	1	@PW  Enable FIB FEE autorange command completed.
Info	03/06/24	22:05:04.371	CSTOL	0	1	@PW  Enabling ICU autorange for FIB with delay count 38400...
Info	03/06/24	22:05:08.367	CSTOL	0	1	@PW  Enable FIB ICU autorange command completed.
Info	03/06/24	22:05:08.448	CSTOL	0	1	@PW  Waiting for sensors to autorange before verification...
Info	03/06/24	22:05:21.230	CSTOL	0	1	@PW  Starting procedure $RCSfile: mag_verif_science.prc,v $
Info	03/06/24	22:05:21.242	CSTOL	0	1	@PW  $Revision: 1.0 $
Info	03/06/24	22:05:21.273	CSTOL	0	1	@PW  Verifying FEE configuration...
Info	03/06/24	22:05:25.447	CSTOL	0	1	@PW  Power packet received. Proceeding to verification.
Info	03/06/24	22:05:29.428	CSTOL	0	1	@PW  Status packet received. Proceeding to verification.
Info	03/06/24	22:05:33.885	CSTOL	0	1	@PW  SID15 packet received. Proceeding to verification.
Info	03/06/24	22:05:34.085	CSTOL	0	1	MAG_HSK_PW MAGORANGE = RANGE1
Info	03/06/24	22:05:34.096	CSTOL	0	1	MAG_HSK_PW MAGIRANGE = RANGE1
Info	03/06/24	22:05:34.108	CSTOL	0	1	MAG_HSK_STATUS FOBSTAT = Active
Info	03/06/24	22:05:34.121	CSTOL	0	1	MAG_HSK_STATUS FIBSTAT = Active
Info	03/06/24	22:05:34.137	CSTOL	0	1	MAG_HSK_STATUS FOBAR = Enabled
Info	03/06/24	22:05:34.148	CSTOL	0	1	MAG_HSK_STATUS FIBAR = Enabled
Info	03/06/24	22:05:34.160	CSTOL	0	1	MAG_HSK_STATUS ICUFOBAR = Enabled
Info	03/06/24	22:05:34.171	CSTOL	0	1	MAG_HSK_STATUS ICUFIBAR = Enabled
Info	03/06/24	22:05:34.181	CSTOL	0	1	@PW  Number of failed tries for FEE activation:
Info	03/06/24	22:05:34.200	CSTOL	0	1	MAG_HSK_SID15 ISV_FOB_ACTTRIES = 1. DN
Info	03/06/24	22:05:34.210	CSTOL	0	1	MAG_HSK_SID15 ISV_FIB_ACTTRIES = 1. DN
Info	03/06/24	22:05:34.243	CSTOL	0	1	@PW  FEEs are active and in a safe configuration. Proceeding to science verification.
Info	03/06/24	22:05:38.341	CSTOL	0	1	@PW  Science snapshot HK packet received. Proceeding to verification.
Info	03/06/24	22:05:38.464	CSTOL	0	1	MAG_HSK_SCI BPRI_OUTRATE = HZ_128
Info	03/06/24	22:05:38.476	CSTOL	0	1	MAG_HSK_SCI BSEC_OUTRATE = HZ_128
Info	03/06/24	22:05:38.487	CSTOL	0	1	MAG_HSK_SID15 ICV_OUTRATE_OBSN = HZ_2
Info	03/06/24	22:05:38.499	CSTOL	0	1	MAG_HSK_SID15 ICV_OUTRATE_IBSN = HZ_2
Info	03/06/24	22:05:38.509	CSTOL	0	1	MAG_HSK_SID15 ICV_OUTRATE_OBSB = HZ_128
Info	03/06/24	22:05:38.526	CSTOL	0	1	MAG_HSK_SID15 ICV_OUTRATE_IBSB = HZ_128
Info	03/06/24	22:05:38.549	CSTOL	0	1	MAG_HSK_PW MAGORANGE = RANGE1
Info	03/06/24	22:05:38.562	CSTOL	0	1	MAG_HSK_PW MAGIRANGE = RANGE1
Info	03/06/24	22:05:38.599	CSTOL	0	1	@PW  MAG generating science and FEEs correctly configured.
Info	03/06/24	22:05:39.246	CSTOL	0	1	@PW  Starting procedure $RCSfile: mag_check_hk.prc,v $
Info	03/06/24	22:05:39.257	CSTOL	0	1	@PW  $Revision: 1.0 $
Info	03/06/24	22:05:39.388	CSTOL	0	1	@PW  Requesting MAG Power HK packet...
Info	03/06/24	22:05:43.420	CSTOL	0	1	@PW  MAG Power HK Report received. Proceeding to verification.
Info	03/06/24	22:05:47.414	CSTOL	0	1	@PW  Status packet received. Proceeding to verification.
Info	03/06/24	22:05:47.726	CSTOL	0	1	MAG_HSK_PW P1V5V = 1.52370834 V
Info	03/06/24	22:05:47.746	CSTOL	0	1	MAG_HSK_PW P1V8V = 1.82973516 V
Info	03/06/24	22:05:47.765	CSTOL	0	1	MAG_HSK_PW P2V5V = 2.54942028 V
Info	03/06/24	22:05:47.776	CSTOL	0	1	MAG_HSK_PW P3V3V = 3.365204948 V
Info	03/06/24	22:05:47.786	CSTOL	0	1	MAG_HSK_PW P8V = 9.573683156 V
Info	03/06/24	22:05:47.798	CSTOL	0	1	MAG_HSK_PW N8V = -9.568713674 V
Info	03/06/24	22:05:47.816	CSTOL	0	1	MAG_HSK_PW P2V4V = 2.354828644 V
Info	03/06/24	22:05:47.828	CSTOL	0	1	MAG_HSK_PW P1V5I = 423.0413716 mA
Info	03/06/24	22:05:47.838	CSTOL	0	1	MAG_HSK_PW P1V8I = 33.07329494 mA
Info	03/06/24	22:05:47.851	CSTOL	0	1	MAG_HSK_PW P2V5I = 94.16220266 mA
Info	03/06/24	22:05:47.868	CSTOL	0	1	MAG_HSK_PW P3V3I = 130.9007113 mA
Info	03/06/24	22:05:47.880	CSTOL	0	1	MAG_HSK_PW P8VI = 193.1202 mA
Info	03/06/24	22:05:47.891	CSTOL	0	1	MAG_HSK_PW N8VI = 154.0556 mA
Info	03/06/24	22:05:47.904	CSTOL	0	1	MAG_HSK_PW ICU_TEMP = 22.0651803 C
Info	03/06/24	22:05:47.915	CSTOL	0	1	MAG_HSK_PW FOB_TEMP = 24.1743591 C
Info	03/06/24	22:05:47.936	CSTOL	0	1	MAG_HSK_PW FIB_TEMP = 24.01458488 C
Info	03/06/24	22:05:47.946	CSTOL	0	1	MAG_HSK_STATUS MAGMODE = Burst
Info	03/06/24	22:05:47.996	CSTOL	0	1	@PW  MAG Power HK parameters within limits. Not in SAFE.
Info	03/06/24	22:05:48.144	CSTOL	0	1	@PW  Sending command to go to Normal 2-2 mode...
Info	03/06/24	22:05:48.867	CSTOL	0	1	@PW  Starting procedure $RCSfile: mag_science.prc,v $
Info	03/06/24	22:05:48.887	CSTOL	0	1	@PW  $Revision: 1.0 $
Info	03/06/24	22:05:53.451	CSTOL	0	1	@PW Normal Mode transition event received. Proceeding to verification.
Info	03/06/24	22:05:53.497	CSTOL	0	1	MAG_PROG_MTRAN EVENT_ID = modeTransition
Info	03/06/24	22:05:53.509	CSTOL	0	1	MAG_PROG_MTRAN PREVM_ID = Config
Info	03/06/24	22:05:53.529	CSTOL	0	1	MAG_PROG_MTRAN CURRM_ID = Normal
Info	03/06/24	22:05:53.562	CSTOL	0	1	@PW  MAG successfully changed mode to Normal
Info	03/06/24	22:05:54.355	CSTOL	0	1	@PW  Starting procedure $RCSfile: mag_verif_science.prc,v $
Info	03/06/24	22:05:54.368	CSTOL	0	1	@PW  $Revision: 1.0 $
Info	03/06/24	22:05:54.390	CSTOL	0	1	@PW  Verifying FEE configuration...
Info	03/06/24	22:05:58.332	CSTOL	0	1	@PW  Power packet received. Proceeding to verification.
Info	03/06/24	22:06:02.328	CSTOL	0	1	@PW  Status packet received. Proceeding to verification.
Info	03/06/24	22:06:06.476	CSTOL	0	1	@PW  SID15 packet received. Proceeding to verification.
Info	03/06/24	22:06:06.664	CSTOL	0	1	MAG_HSK_PW MAGORANGE = RANGE2
Info	03/06/24	22:06:06.676	CSTOL	0	1	MAG_HSK_PW MAGIRANGE = RANGE2
Info	03/06/24	22:06:06.694	CSTOL	0	1	MAG_HSK_STATUS FOBSTAT = Active
Info	03/06/24	22:06:06.706	CSTOL	0	1	MAG_HSK_STATUS FIBSTAT = Active
Info	03/06/24	22:06:06.717	CSTOL	0	1	MAG_HSK_STATUS FOBAR = Enabled
Info	03/06/24	22:06:06.729	CSTOL	0	1	MAG_HSK_STATUS FIBAR = Enabled
Info	03/06/24	22:06:06.749	CSTOL	0	1	MAG_HSK_STATUS ICUFOBAR = Enabled
Info	03/06/24	22:06:06.759	CSTOL	0	1	MAG_HSK_STATUS ICUFIBAR = Enabled
Info	03/06/24	22:06:06.770	CSTOL	0	1	@PW  Number of failed tries for FEE activation:
Info	03/06/24	22:06:06.780	CSTOL	0	1	MAG_HSK_SID15 ISV_FOB_ACTTRIES = 1. DN
Info	03/06/24	22:06:06.792	CSTOL	0	1	MAG_HSK_SID15 ISV_FIB_ACTTRIES = 1. DN
Info	03/06/24	22:06:06.828	CSTOL	0	1	@PW  FEEs are active and in a safe configuration. Proceeding to science verification.
Info	03/06/24	22:06:10.354	CSTOL	0	1	@PW  Science snapshot HK packet received. Proceeding to verification.
Info	03/06/24	22:06:10.499	CSTOL	0	1	MAG_HSK_SCI NPRI_OUTRATE = HZ_2
Info	03/06/24	22:06:10.509	CSTOL	0	1	MAG_HSK_SCI NSEC_OUTRATE = HZ_2
Info	03/06/24	22:06:10.522	CSTOL	0	1	MAG_HSK_SID15 ICV_OUTRATE_OBSN = HZ_2
Info	03/06/24	22:06:10.532	CSTOL	0	1	MAG_HSK_SID15 ICV_OUTRATE_IBSN = HZ_2
Info	03/06/24	22:06:10.543	CSTOL	0	1	MAG_HSK_SID15 ICV_OUTRATE_OBSB = HZ_64
Info	03/06/24	22:06:10.559	CSTOL	0	1	MAG_HSK_SID15 ICV_OUTRATE_IBSB = HZ_64
Info	03/06/24	22:06:10.581	CSTOL	0	1	MAG_HSK_PW MAGORANGE = RANGE2
Info	03/06/24	22:06:10.592	CSTOL	0	1	MAG_HSK_PW MAGIRANGE = RANGE2
Info	03/06/24	22:06:10.634	CSTOL	0	1	@PW  MAG generating science and FEEs correctly configured.
Info	03/06/24	22:26:11.447	CSTOL	0	1	@PW  Sending command to go to Burst 64-8 mode for 1200 seconds...
Info	03/06/24	22:26:12.130	CSTOL	0	1	@PW  Starting procedure $RCSfile: mag_science.prc,v $
Info	03/06/24	22:26:12.141	CSTOL	0	1	@PW  $Revision: 1.0 $
Info	03/06/24	22:26:17.305	CSTOL	0	1	@PW Burst Mode transition event received. Proceeding to verification.
Info	03/06/24	22:26:17.346	CSTOL	0	1	MAG_PROG_MTRAN EVENT_ID = modeTransition
Info	03/06/24	22:26:17.358	CSTOL	0	1	MAG_PROG_MTRAN PREVM_ID = Config
Info	03/06/24	22:26:17.374	CSTOL	0	1	MAG_PROG_MTRAN CURRM_ID = Burst
Info	03/06/24	22:26:17.407	CSTOL	0	1	@PW  MAG successfully changed mode to Burst
Info	03/06/24	22:26:18.119	CSTOL	0	1	@PW  Starting procedure $RCSfile: mag_verif_science.prc,v $
Info	03/06/24	22:26:18.131	CSTOL	0	1	@PW  $Revision: 1.0 $
Info	03/06/24	22:26:18.153	CSTOL	0	1	@PW  Verifying FEE configuration...
Info	03/06/24	22:26:22.240	CSTOL	0	1	@PW  Power packet received. Proceeding to verification.
Info	03/06/24	22:26:26.243	CSTOL	0	1	@PW  Status packet received. Proceeding to verification.
Info	03/06/24	22:26:30.430	CSTOL	0	1	@PW  SID15 packet received. Proceeding to verification.
Info	03/06/24	22:26:30.627	CSTOL	0	1	MAG_HSK_PW MAGORANGE = RANGE3
Info	03/06/24	22:26:30.638	CSTOL	0	1	MAG_HSK_PW MAGIRANGE = RANGE3
Info	03/06/24	22:26:30.648	CSTOL	0	1	MAG_HSK_STATUS FOBSTAT = Active
Info	03/06/24	22:26:30.661	CSTOL	0	1	MAG_HSK_STATUS FIBSTAT = Active
Info	03/06/24	22:26:30.671	CSTOL	0	1	MAG_HSK_STATUS FOBAR = Enabled
Info	03/06/24	22:26:30.680	CSTOL	0	1	MAG_HSK_STATUS FIBAR = Enabled
Info	03/06/24	22:26:30.698	CSTOL	0	1	MAG_HSK_STATUS ICUFOBAR = Enabled
Info	03/06/24	22:26:30.710	CSTOL	0	1	MAG_HSK_STATUS ICUFIBAR = Enabled
Info	03/06/24	22:26:30.721	CSTOL	0	1	@PW  Number of failed tries for FEE activation:
Info	03/06/24	22:26:30.733	CSTOL	0	1	MAG_HSK_SID15 ISV_FOB_ACTTRIES = 1. DN
Info	03/06/24	22:26:30.744	CSTOL	0	1	MAG_HSK_SID15 ISV_FIB_ACTTRIES = 1. DN
Info	03/06/24	22:26:30.783	CSTOL	0	1	@PW  FEEs are active and in a safe configuration. Proceeding to science verification.
Info	03/06/24	22:26:34.250	CSTOL	0	1	@PW  Science snapshot HK packet received. Proceeding to verification.
Info	03/06/24	22:26:34.378	CSTOL	0	1	MAG_HSK_SCI BPRI_OUTRATE = HZ_64
Info	03/06/24	22:26:34.391	CSTOL	0	1	MAG_HSK_SCI BSEC_OUTRATE = HZ_8
Info	03/06/24	22:26:34.401	CSTOL	0	1	MAG_HSK_SID15 ICV_OUTRATE_OBSN = HZ_2
Info	03/06/24	22:26:34.413	CSTOL	0	1	MAG_HSK_SID15 ICV_OUTRATE_IBSN = HZ_2
Info	03/06/24	22:26:34.424	CSTOL	0	1	MAG_HSK_SID15 ICV_OUTRATE_OBSB = HZ_64
Info	03/06/24	22:26:34.437	CSTOL	0	1	MAG_HSK_SID15 ICV_OUTRATE_IBSB = HZ_8
Info	03/06/24	22:26:34.460	CSTOL	0	1	MAG_HSK_PW MAGORANGE = RANGE3
Info	03/06/24	22:26:34.470	CSTOL	0	1	MAG_HSK_PW MAGIRANGE = RANGE3
Info	03/06/24	22:26:34.509	CSTOL	0	1	@PW  MAG generating science and FEEs correctly configured.
Info	03/06/24	22:26:34.585	CSTOL	0	1	@PW  Waiting for automatic exit from Burst mode...
Info	03/06/24	22:46:25.167	CSTOL	0	1	MAG_PROG_MTRAN EVENT_ID = modeTransition
Info	03/06/24	22:46:25.178	CSTOL	0	1	MAG_PROG_MTRAN PREVM_ID = Burst
Info	03/06/24	22:46:25.197	CSTOL	0	1	MAG_PROG_MTRAN CURRM_ID = Normal
Info	03/06/24	22:46:25.230	CSTOL	0	1	@PW  Burst to Normal Mode transition event received. Proceeding to verification.
Info	03/06/24	22:46:25.423	CSTOL	0	1	@PW  Sending command to go to Normal 4-1 mode...
Info	03/06/24	22:46:26.153	CSTOL	0	1	@PW  Starting procedure $RCSfile: mag_science.prc,v $
Info	03/06/24	22:46:26.163	CSTOL	0	1	@PW  $Revision: 1.0 $
Info	03/06/24	22:46:26.401	CSTOL	0	1	@PW Normal Mode transition event received. Proceeding to verification.
Info	03/06/24	22:46:26.441	CSTOL	0	1	MAG_PROG_MTRAN EVENT_ID = modeTransition
Info	03/06/24	22:46:26.453	CSTOL	0	1	MAG_PROG_MTRAN PREVM_ID = Burst
Info	03/06/24	22:46:26.467	CSTOL	0	1	MAG_PROG_MTRAN CURRM_ID = Normal
Info	03/06/24	22:46:26.499	CSTOL	0	1	@PW  MAG successfully changed mode to Normal
Info	03/06/24	22:46:27.250	CSTOL	0	1	@PW  Starting procedure $RCSfile: mag_verif_science.prc,v $
Info	03/06/24	22:46:27.260	CSTOL	0	1	@PW  $Revision: 1.0 $
Info	03/06/24	22:46:27.282	CSTOL	0	1	@PW  Verifying FEE configuration...
Info	03/06/24	22:46:32.154	CSTOL	0	1	@PW  Power packet received. Proceeding to verification.
Info	03/06/24	22:46:36.178	CSTOL	0	1	@PW  Status packet received. Proceeding to verification.
Info	03/06/24	22:46:40.322	CSTOL	0	1	@PW  SID15 packet received. Proceeding to verification.
Info	03/06/24	22:46:40.506	CSTOL	0	1	MAG_HSK_PW MAGORANGE = RANGE3
Info	03/06/24	22:46:40.517	CSTOL	0	1	MAG_HSK_PW MAGIRANGE = RANGE3
Info	03/06/24	22:46:40.530	CSTOL	0	1	MAG_HSK_STATUS FOBSTAT = Active
Info	03/06/24	22:46:40.542	CSTOL	0	1	MAG_HSK_STATUS FIBSTAT = Active
Info	03/06/24	22:46:40.552	CSTOL	0	1	MAG_HSK_STATUS FOBAR = Enabled
Info	03/06/24	22:46:40.563	CSTOL	0	1	MAG_HSK_STATUS FIBAR = Enabled
Info	03/06/24	22:46:40.575	CSTOL	0	1	MAG_HSK_STATUS ICUFOBAR = Enabled
Info	03/06/24	22:46:40.589	CSTOL	0	1	MAG_HSK_STATUS ICUFIBAR = Enabled
Info	03/06/24	22:46:40.601	CSTOL	0	1	@PW  Number of failed tries for FEE activation:
Info	03/06/24	22:46:40.611	CSTOL	0	1	MAG_HSK_SID15 ISV_FOB_ACTTRIES = 1. DN
Info	03/06/24	22:46:40.621	CSTOL	0	1	MAG_HSK_SID15 ISV_FIB_ACTTRIES = 1. DN
Info	03/06/24	22:46:40.664	CSTOL	0	1	@PW  FEEs are active and in a safe configuration. Proceeding to science verification.
Info	03/06/24	22:46:44.158	CSTOL	0	1	@PW  Science snapshot HK packet received. Proceeding to verification.
Info	03/06/24	22:46:44.305	CSTOL	0	1	MAG_HSK_SCI NPRI_OUTRATE = HZ_4
Info	03/06/24	22:46:44.316	CSTOL	0	1	MAG_HSK_SCI NSEC_OUTRATE = HZ_1
Info	03/06/24	22:46:44.328	CSTOL	0	1	MAG_HSK_SID15 ICV_OUTRATE_OBSN = HZ_4
Info	03/06/24	22:46:44.341	CSTOL	0	1	MAG_HSK_SID15 ICV_OUTRATE_IBSN = HZ_1
Info	03/06/24	22:46:44.357	CSTOL	0	1	MAG_HSK_SID15 ICV_OUTRATE_OBSB = HZ_64
Info	03/06/24	22:46:44.368	CSTOL	0	1	MAG_HSK_SID15 ICV_OUTRATE_IBSB = HZ_64
Info	03/06/24	22:46:44.391	CSTOL	0	1	MAG_HSK_PW MAGORANGE = RANGE3
Info	03/06/24	22:46:44.401	CSTOL	0	1	MAG_HSK_PW MAGIRANGE = RANGE3
Info	03/06/24	22:46:44.438	CSTOL	0	1	@PW  MAG generating science and FEEs correctly configured.
Info	03/06/24	23:06:44.664	CSTOL	0	1	@PW  Sending command to go to Burst 64-64 mode for 1200 seconds...
Info	03/06/24	23:06:45.346	CSTOL	0	1	@PW  Starting procedure $RCSfile: mag_science.prc,v $
Info	03/06/24	23:06:45.358	CSTOL	0	1	@PW  $Revision: 1.0 $
Info	03/06/24	23:06:49.167	CSTOL	0	1	@PW Burst Mode transition event received. Proceeding to verification.
Info	03/06/24	23:06:49.210	CSTOL	0	1	MAG_PROG_MTRAN EVENT_ID = modeTransition
Info	03/06/24	23:06:49.229	CSTOL	0	1	MAG_PROG_MTRAN PREVM_ID = Normal
Info	03/06/24	23:06:49.240	CSTOL	0	1	MAG_PROG_MTRAN CURRM_ID = Burst
Info	03/06/24	23:06:49.270	CSTOL	0	1	@PW  MAG successfully changed mode to Burst
Info	03/06/24	23:06:50.094	CSTOL	0	1	@PW  Starting procedure $RCSfile: mag_verif_science.prc,v $
Info	03/06/24	23:06:50.105	CSTOL	0	1	@PW  $Revision: 1.0 $
Info	03/06/24	23:06:50.135	CSTOL	0	1	@PW  Verifying FEE configuration...
Info	03/06/24	23:06:52.076	CSTOL	0	1	@PW  Power packet received. Proceeding to verification.
Info	03/06/24	23:06:56.088	CSTOL	0	1	@PW  Status packet received. Proceeding to verification.
Info	03/06/24	23:07:00.230	CSTOL	0	1	@PW  SID15 packet received. Proceeding to verification.
Info	03/06/24	23:07:00.434	CSTOL	0	1	MAG_HSK_PW MAGORANGE = RANGE3
Info	03/06/24	23:07:00.446	CSTOL	0	1	MAG_HSK_PW MAGIRANGE = RANGE3
Info	03/06/24	23:07:00.456	CSTOL	0	1	MAG_HSK_STATUS FOBSTAT = Active
Info	03/06/24	23:07:00.467	CSTOL	0	1	MAG_HSK_STATUS FIBSTAT = Active
Info	03/06/24	23:07:00.479	CSTOL	0	1	MAG_HSK_STATUS FOBAR = Enabled
Info	03/06/24	23:07:00.496	CSTOL	0	1	MAG_HSK_STATUS FIBAR = Enabled
Info	03/06/24	23:07:00.507	CSTOL	0	1	MAG_HSK_STATUS ICUFOBAR = Enabled
Info	03/06/24	23:07:00.519	CSTOL	0	1	MAG_HSK_STATUS ICUFIBAR = Enabled
Info	03/06/24	23:07:00.529	CSTOL	0	1	@PW  Number of failed tries for FEE activation:
Info	03/06/24	23:07:00.540	CSTOL	0	1	MAG_HSK_SID15 ISV_FOB_ACTTRIES = 1. DN
Info	03/06/24	23:07:00.555	CSTOL	0	1	MAG_HSK_SID15 ISV_FIB_ACTTRIES = 1. DN
Info	03/06/24	23:07:00.588	CSTOL	0	1	@PW  FEEs are active and in a safe configuration. Proceeding to science verification.
Info	03/06/24	23:07:04.118	CSTOL	0	1	@PW  Science snapshot HK packet received. Proceeding to verification.
Info	03/06/24	23:07:04.243	CSTOL	0	1	MAG_HSK_SCI BPRI_OUTRATE = HZ_64
Info	03/06/24	23:07:04.253	CSTOL	0	1	MAG_HSK_SCI BSEC_OUTRATE = HZ_64
Info	03/06/24	23:07:04.266	CSTOL	0	1	MAG_HSK_SID15 ICV_OUTRATE_OBSN = HZ_4
Info	03/06/24	23:07:04.276	CSTOL	0	1	MAG_HSK_SID15 ICV_OUTRATE_IBSN = HZ_1
Info	03/06/24	23:07:04.288	CSTOL	0	1	MAG_HSK_SID15 ICV_OUTRATE_OBSB = HZ_64
Info	03/06/24	23:07:04.306	CSTOL	0	1	MAG_HSK_SID15 ICV_OUTRATE_IBSB = HZ_64
Info	03/06/24	23:07:04.329	CSTOL	0	1	MAG_HSK_PW MAGORANGE = RANGE3
Info	03/06/24	23:07:04.341	CSTOL	0	1	MAG_HSK_PW MAGIRANGE = RANGE3
Info	03/06/24	23:07:04.375	CSTOL	0	1	@PW  MAG generating science and FEEs correctly configured.
Info	03/06/24	23:07:04.456	CSTOL	0	1	@PW  Waiting for automatic exit from Burst mode...
Info	03/06/24	23:26:56.023	CSTOL	0	1	MAG_PROG_MTRAN EVENT_ID = modeTransition
Info	03/06/24	23:26:56.042	CSTOL	0	1	MAG_PROG_MTRAN PREVM_ID = Burst
Info	03/06/24	23:26:56.052	CSTOL	0	1	MAG_PROG_MTRAN CURRM_ID = Normal
Info	03/06/24	23:26:56.085	CSTOL	0	1	@PW  Burst to Normal Mode transition event received. Proceeding to verification.
Info	03/06/24	23:26:56.135	CSTOL	0	1	@PW  Sending command to go to Normal 4-4 mode...
Info	03/06/24	23:26:57.016	CSTOL	0	1	@PW  Starting procedure $RCSfile: mag_science.prc,v $
Info	03/06/24	23:26:57.028	CSTOL	0	1	@PW  $Revision: 1.0 $
Info	03/06/24	23:26:57.266	CSTOL	0	1	@PW Normal Mode transition event received. Proceeding to verification.
Info	03/06/24	23:26:57.319	CSTOL	0	1	MAG_PROG_MTRAN EVENT_ID = modeTransition
Info	03/06/24	23:26:57.331	CSTOL	0	1	MAG_PROG_MTRAN PREVM_ID = Burst
Info	03/06/24	23:26:57.341	CSTOL	0	1	MAG_PROG_MTRAN CURRM_ID = Normal
Info	03/06/24	23:26:57.381	CSTOL	0	1	@PW  MAG successfully changed mode to Normal
Info	03/06/24	23:26:58.141	CSTOL	0	1	@PW  Starting procedure $RCSfile: mag_verif_science.prc,v $
Info	03/06/24	23:26:58.153	CSTOL	0	1	@PW  $Revision: 1.0 $
Info	03/06/24	23:26:58.174	CSTOL	0	1	@PW  Verifying FEE configuration...
Info	03/06/24	23:27:04.068	CSTOL	0	1	@PW  Power packet received. Proceeding to verification.
Info	03/06/24	23:27:07.963	CSTOL	0	1	@PW  Status packet received. Proceeding to verification.
Info	03/06/24	23:27:12.198	CSTOL	0	1	@PW  SID15 packet received. Proceeding to verification.
Info	03/06/24	23:27:12.437	CSTOL	0	1	MAG_HSK_PW MAGORANGE = RANGE3
Info	03/06/24	23:27:12.451	CSTOL	0	1	MAG_HSK_PW MAGIRANGE = RANGE3
Info	03/06/24	23:27:12.461	CSTOL	0	1	MAG_HSK_STATUS FOBSTAT = Active
Info	03/06/24	23:27:12.474	CSTOL	0	1	MAG_HSK_STATUS FIBSTAT = Active
Info	03/06/24	23:27:12.484	CSTOL	0	1	MAG_HSK_STATUS FOBAR = Enabled
Info	03/06/24	23:27:12.496	CSTOL	0	1	MAG_HSK_STATUS FIBAR = Enabled
Info	03/06/24	23:27:12.510	CSTOL	0	1	MAG_HSK_STATUS ICUFOBAR = Enabled
Info	03/06/24	23:27:12.520	CSTOL	0	1	MAG_HSK_STATUS ICUFIBAR = Enabled
Info	03/06/24	23:27:12.532	CSTOL	0	1	@PW  Number of failed tries for FEE activation:
Info	03/06/24	23:27:12.542	CSTOL	0	1	MAG_HSK_SID15 ISV_FOB_ACTTRIES = 1. DN
Info	03/06/24	23:27:12.553	CSTOL	0	1	MAG_HSK_SID15 ISV_FIB_ACTTRIES = 1. DN
Info	03/06/24	23:27:12.594	CSTOL	0	1	@PW  FEEs are active and in a safe configuration. Proceeding to science verification.
Info	03/06/24	23:27:16.016	CSTOL	0	1	@PW  Science snapshot HK packet received. Proceeding to verification.
Info	03/06/24	23:27:16.163	CSTOL	0	1	MAG_HSK_SCI NPRI_OUTRATE = HZ_4
Info	03/06/24	23:27:16.174	CSTOL	0	1	MAG_HSK_SCI NSEC_OUTRATE = HZ_4
Info	03/06/24	23:27:16.184	CSTOL	0	1	MAG_HSK_SID15 ICV_OUTRATE_OBSN = HZ_4
Info	03/06/24	23:27:16.196	CSTOL	0	1	MAG_HSK_SID15 ICV_OUTRATE_IBSN = HZ_4
Info	03/06/24	23:27:16.211	CSTOL	0	1	MAG_HSK_SID15 ICV_OUTRATE_OBSB = HZ_128
Info	03/06/24	23:27:16.221	CSTOL	0	1	MAG_HSK_SID15 ICV_OUTRATE_IBSB = HZ_128
Info	03/06/24	23:27:16.243	CSTOL	0	1	MAG_HSK_PW MAGORANGE = RANGE3
Info	03/06/24	23:27:16.253	CSTOL	0	1	MAG_HSK_PW MAGIRANGE = RANGE3
Info	03/06/24	23:27:16.288	CSTOL	0	1	@PW  MAG generating science and FEEs correctly configured.
Info	03/06/24	23:47:17.119	CSTOL	0	1	@PW  Sending command to go to Burst 128-128 mode...
Info	03/06/24	23:47:17.150	CSTOL	0	1	@PW  Sending command to go to Burst 128-128 mode for 1200 seconds...
Info	03/06/24	23:47:17.877	CSTOL	0	1	@PW  Starting procedure $RCSfile: mag_science.prc,v $
Info	03/06/24	23:47:17.888	CSTOL	0	1	@PW  $Revision: 1.0 $
Info	03/06/24	23:47:21.980	CSTOL	0	1	@PW Burst Mode transition event received. Proceeding to verification.
Info	03/06/24	23:47:22.026	CSTOL	0	1	MAG_PROG_MTRAN EVENT_ID = modeTransition
Info	03/06/24	23:47:22.038	CSTOL	0	1	MAG_PROG_MTRAN PREVM_ID = Normal
Info	03/06/24	23:47:22.056	CSTOL	0	1	MAG_PROG_MTRAN CURRM_ID = Burst
Info	03/06/24	23:47:22.089	CSTOL	0	1	@PW  MAG successfully changed mode to Burst
Info	03/06/24	23:47:23.012	CSTOL	0	1	@PW  Starting procedure $RCSfile: mag_verif_science.prc,v $
Info	03/06/24	23:47:23.023	CSTOL	0	1	@PW  $Revision: 1.0 $
Info	03/06/24	23:47:23.045	CSTOL	0	1	@PW  Verifying FEE configuration...
Info	03/06/24	23:47:27.980	CSTOL	0	1	@PW  Power packet received. Proceeding to verification.
Info	03/06/24	23:47:32.010	CSTOL	0	1	@PW  Status packet received. Proceeding to verification.
Info	03/06/24	23:47:36.428	CSTOL	0	1	@PW  SID15 packet received. Proceeding to verification.
Info	03/06/24	23:47:36.753	CSTOL	0	1	MAG_HSK_PW MAGORANGE = RANGE3
Info	03/06/24	23:47:36.765	CSTOL	0	1	MAG_HSK_PW MAGIRANGE = RANGE3
Info	03/06/24	23:47:36.776	CSTOL	0	1	MAG_HSK_STATUS FOBSTAT = Active
Info	03/06/24	23:47:36.790	CSTOL	0	1	MAG_HSK_STATUS FIBSTAT = Active
Info	03/06/24	23:47:36.802	CSTOL	0	1	MAG_HSK_STATUS FOBAR = Enabled
Info	03/06/24	23:47:36.812	CSTOL	0	1	MAG_HSK_STATUS FIBAR = Enabled
Info	03/06/24	23:47:36.825	CSTOL	0	1	MAG_HSK_STATUS ICUFOBAR = Enabled
Info	03/06/24	23:47:36.835	CSTOL	0	1	MAG_HSK_STATUS ICUFIBAR = Enabled
Info	03/06/24	23:47:36.846	CSTOL	0	1	@PW  Number of failed tries for FEE activation:
Info	03/06/24	23:47:36.871	CSTOL	0	1	MAG_HSK_SID15 ISV_FOB_ACTTRIES = 1. DN
Info	03/06/24	23:47:36.882	CSTOL	0	1	MAG_HSK_SID15 ISV_FIB_ACTTRIES = 1. DN
Info	03/06/24	23:47:36.914	CSTOL	0	1	@PW  FEEs are active and in a safe configuration. Proceeding to science verification.
Info	03/06/24	23:47:40.917	CSTOL	0	1	@PW  Science snapshot HK packet received. Proceeding to verification.
Info	03/06/24	23:47:41.059	CSTOL	0	1	MAG_HSK_SCI BPRI_OUTRATE = HZ_128
Info	03/06/24	23:47:41.072	CSTOL	0	1	MAG_HSK_SCI BSEC_OUTRATE = HZ_128
Info	03/06/24	23:47:41.082	CSTOL	0	1	MAG_HSK_SID15 ICV_OUTRATE_OBSN = HZ_4
Info	03/06/24	23:47:41.094	CSTOL	0	1	MAG_HSK_SID15 ICV_OUTRATE_IBSN = HZ_4
Info	03/06/24	23:47:41.105	CSTOL	0	1	MAG_HSK_SID15 ICV_OUTRATE_OBSB = HZ_128
Info	03/06/24	23:47:41.121	CSTOL	0	1	MAG_HSK_SID15 ICV_OUTRATE_IBSB = HZ_128
Info	03/06/24	23:47:41.144	CSTOL	0	1	MAG_HSK_PW MAGORANGE = RANGE3
Info	03/06/24	23:47:41.154	CSTOL	0	1	MAG_HSK_PW MAGIRANGE = RANGE3
Info	03/06/24	23:47:41.196	CSTOL	0	1	@PW  MAG generating science and FEEs correctly configured.
Info	03/07/24	00:07:41.950	CSTOL	0	1	@PW  Checking range of the two sensors...
Info	03/07/24	00:07:42.023	CSTOL	0	1	@PW  MAGo and MAGi confirmed to be in Range 3. Starting range cycling...
Info	03/07/24	00:07:42.161	CSTOL	0	1	@PW  Waiting 5 seconds to allow user to abort ranging...
Info	03/07/24	00:07:47.921	CSTOL	0	1	@PW  Starting procedure $RCSfile: mag_change_range.prc,v $
Info	03/07/24	00:07:47.933	CSTOL	0	1	@PW  $Revision: 1.0 $
Info	03/07/24	00:07:48.006	CSTOL	0	1	@PW  Disabling ICU autorange for FOB...
Info	03/07/24	00:07:51.878	CSTOL	0	1	@PW  Disable FOB ICU autorange command completed.
Info	03/07/24	00:07:51.973	CSTOL	0	1	@PW  Disabling FEE autorange for FOB...
Info	03/07/24	00:07:55.884	CSTOL	0	1	@PW  Disable FOB FEE autorange command completed.
Info	03/07/24	00:07:55.934	CSTOL	0	1	@PW  Commanding FOB MAG into RANGE2
Info	03/07/24	00:07:55.946	CSTOL	0	1	@PW  with all Gains set to 3...
Info	03/07/24	00:07:59.878	CSTOL	0	1	@PW  Command FOB into RANGE2 completed.
Info	03/07/24	00:07:59.966	CSTOL	0	1	@PW  Re-enabling FEE autorange for FOB with AR delay S50...
Info	03/07/24	00:08:03.888	CSTOL	0	1	@PW  Re-enable FOB FEE autorange command completed.
Info	03/07/24	00:08:07.878	CSTOL	0	1	@PW  Power packet received. Proceeding to verification.
Info	03/07/24	00:08:12.349	CSTOL	0	1	@PW  SID15 packet received. Proceeding to verification.
Info	03/07/24	00:08:12.371	CSTOL	0	1	MAG_HSK_SID15 ICV_FIB_RG0GAINX = 3. DN
Info	03/07/24	00:08:12.384	CSTOL	0	1	MAG_HSK_SID15 ICV_FIB_RG0GAINY = 3. DN
Info	03/07/24	00:08:12.400	CSTOL	0	1	MAG_HSK_SID15 ICV_FIB_RG0GAINZ = 3. DN
Info	03/07/24	00:08:12.411	CSTOL	0	1	MAG_HSK_SID15 ICV_FIB_RG1GAINX = 3. DN
Info	03/07/24	00:08:12.423	CSTOL	0	1	MAG_HSK_SID15 ICV_FIB_RG1GAINY = 3. DN
Info	03/07/24	00:08:12.434	CSTOL	0	1	MAG_HSK_SID15 ICV_FIB_RG1GAINZ = 3. DN
Info	03/07/24	00:08:12.447	CSTOL	0	1	MAG_HSK_SID15 ICV_FIB_RG2GAINX = 3. DN
Info	03/07/24	00:08:12.464	CSTOL	0	1	MAG_HSK_SID15 ICV_FIB_RG2GAINY = 3. DN
Info	03/07/24	00:08:12.476	CSTOL	0	1	MAG_HSK_SID15 ICV_FIB_RG2GAINZ = 3. DN
Info	03/07/24	00:08:12.489	CSTOL	0	1	MAG_HSK_SID15 ICV_FIB_RG3GAINX = 3. DN
Info	03/07/24	00:08:12.500	CSTOL	0	1	MAG_HSK_SID15 ICV_FIB_RG3GAINY = 3. DN
Info	03/07/24	00:08:12.512	CSTOL	0	1	MAG_HSK_SID15 ICV_FIB_RG3GAINZ = 3. DN
Info	03/07/24	00:08:12.742	CSTOL	0	1	MAG_HSK_PW MAGORANGE = RANGE2
Info	03/07/24	00:08:12.753	CSTOL	0	1	MAG_HSK_PW MAGIRANGE = RANGE3
Info	03/07/24	00:08:12.789	CSTOL	0	1	@PW  Range change completed successfully.
Info	03/07/24	00:18:14.219	CSTOL	0	1	@PW  Starting procedure $RCSfile: mag_change_range.prc,v $
Info	03/07/24	00:18:14.236	CSTOL	0	1	@PW  $Revision: 1.0 $
Info	03/07/24	00:18:14.446	CSTOL	0	1	@PW  Disabling ICU autorange for FIB...
Info	03/07/24	00:18:17.838	CSTOL	0	1	@PW  Disable FIB ICU autorange command completed.
Info	03/07/24	00:18:17.927	CSTOL	0	1	@PW  Disabling FEE autorange for FIB...
Info	03/07/24	00:18:21.836	CSTOL	0	1	@PW  Disable FIB FEE autorange command completed.
Info	03/07/24	00:18:21.888	CSTOL	0	1	@PW  Commanding FIB MAG into RANGE2
Info	03/07/24	00:18:21.900	CSTOL	0	1	@PW  with all Gains set to 3...
Info	03/07/24	00:18:25.832	CSTOL	0	1	@PW  Command FIB into RANGE2 completed.
Info	03/07/24	00:18:25.918	CSTOL	0	1	@PW  Re-enabling FEE autorange for FIB with AR delay S50...
Info	03/07/24	00:18:29.838	CSTOL	0	1	@PW  Re-enable FIB FEE autorange command completed.
Info	03/07/24	00:18:31.864	CSTOL	0	1	@PW  Power packet received. Proceeding to verification.
Info	03/07/24	00:18:36.269	CSTOL	0	1	@PW  SID15 packet received. Proceeding to verification.
Info	03/07/24	00:18:36.295	CSTOL	0	1	MAG_HSK_SID15 ICV_FIB_RG0GAINX = 3. DN
Info	03/07/24	00:18:36.305	CSTOL	0	1	MAG_HSK_SID15 ICV_FIB_RG0GAINY = 3. DN
Info	03/07/24	00:18:36.323	CSTOL	0	1	MAG_HSK_SID15 ICV_FIB_RG0GAINZ = 3. DN
Info	03/07/24	00:18:36.335	CSTOL	0	1	MAG_HSK_SID15 ICV_FIB_RG1GAINX = 3. DN
Info	03/07/24	00:18:36.346	CSTOL	0	1	MAG_HSK_SID15 ICV_FIB_RG1GAINY = 3. DN
Info	03/07/24	00:18:36.358	CSTOL	0	1	MAG_HSK_SID15 ICV_FIB_RG1GAINZ = 3. DN
Info	03/07/24	00:18:36.369	CSTOL	0	1	MAG_HSK_SID15 ICV_FIB_RG2GAINX = 3. DN
Info	03/07/24	00:18:36.385	CSTOL	0	1	MAG_HSK_SID15 ICV_FIB_RG2GAINY = 3. DN
Info	03/07/24	00:18:36.397	CSTOL	0	1	MAG_HSK_SID15 ICV_FIB_RG2GAINZ = 3. DN
Info	03/07/24	00:18:36.408	CSTOL	0	1	MAG_HSK_SID15 ICV_FIB_RG3GAINX = 3. DN
Info	03/07/24	00:18:36.421	CSTOL	0	1	MAG_HSK_SID15 ICV_FIB_RG3GAINY = 3. DN
Info	03/07/24	00:18:36.431	CSTOL	0	1	MAG_HSK_SID15 ICV_FIB_RG3GAINZ = 3. DN
Info	03/07/24	00:18:36.592	CSTOL	0	1	MAG_HSK_PW MAGORANGE = RANGE2
Info	03/07/24	00:18:36.604	CSTOL	0	1	MAG_HSK_PW MAGIRANGE = RANGE2
Info	03/07/24	00:18:36.644	CSTOL	0	1	@PW  Range change completed successfully.
Info	03/07/24	00:18:40.763	CSTOL	0	1	@PW  Status packet received. Proceeding to verification.
Info	03/07/24	00:18:40.885	CSTOL	0	1	MAG_HSK_STATUS MAGMODE = Burst
Info	03/07/24	00:18:40.930	CSTOL	0	1	@PW  MAG autoranging correctly configured.
Info	03/07/24	00:28:42.190	CSTOL	0	1	@PW  Starting procedure $RCSfile: mag_change_range.prc,v $
Info	03/07/24	00:28:42.201	CSTOL	0	1	@PW  $Revision: 1.0 $
Info	03/07/24	00:28:42.276	CSTOL	0	1	@PW  Disabling ICU autorange for FOB...
Info	03/07/24	00:28:45.788	CSTOL	0	1	@PW  Disable FOB ICU autorange command completed.
Info	03/07/24	00:28:45.881	CSTOL	0	1	@PW  Disabling FEE autorange for FOB...
Info	03/07/24	00:28:49.782	CSTOL	0	1	@PW  Disable FOB FEE autorange command completed.
Info	03/07/24	00:28:49.832	CSTOL	0	1	@PW  Commanding FOB MAG into RANGE1
Info	03/07/24	00:28:49.842	CSTOL	0	1	@PW  with all Gains set to 3...
Info	03/07/24	00:28:53.785	CSTOL	0	1	@PW  Command FOB into RANGE1 completed.
Info	03/07/24	00:28:53.872	CSTOL	0	1	@PW  Re-enabling FEE autorange for FOB with AR delay S50...
Info	03/07/24	00:28:57.793	CSTOL	0	1	@PW  Re-enable FOB FEE autorange command completed.
Info	03/07/24	00:29:01.786	CSTOL	0	1	@PW  Power packet received. Proceeding to verification.
Info	03/07/24	00:29:06.244	CSTOL	0	1	@PW  SID15 packet received. Proceeding to verification.
Info	03/07/24	00:29:06.266	CSTOL	0	1	MAG_HSK_SID15 ICV_FIB_RG0GAINX = 3. DN
Info	03/07/24	00:29:06.279	CSTOL	0	1	MAG_HSK_SID15 ICV_FIB_RG0GAINY = 3. DN
Info	03/07/24	00:29:06.289	CSTOL	0	1	MAG_HSK_SID15 ICV_FIB_RG0GAINZ = 3. DN
Info	03/07/24	00:29:06.306	CSTOL	0	1	MAG_HSK_SID15 ICV_FIB_RG1GAINX = 3. DN
Info	03/07/24	00:29:06.319	CSTOL	0	1	MAG_HSK_SID15 ICV_FIB_RG1GAINY = 3. DN
Info	03/07/24	00:29:06.331	CSTOL	0	1	MAG_HSK_SID15 ICV_FIB_RG1GAINZ = 3. DN
Info	03/07/24	00:29:06.342	CSTOL	0	1	MAG_HSK_SID15 ICV_FIB_RG2GAINX = 3. DN
Info	03/07/24	00:29:06.354	CSTOL	0	1	MAG_HSK_SID15 ICV_FIB_RG2GAINY = 3. DN
Info	03/07/24	00:29:06.368	CSTOL	0	1	MAG_HSK_SID15 ICV_FIB_RG2GAINZ = 3. DN
Info	03/07/24	00:29:06.381	CSTOL	0	1	MAG_HSK_SID15 ICV_FIB_RG3GAINX = 3. DN
Info	03/07/24	00:29:06.434	CSTOL	0	1	MAG_HSK_SID15 ICV_FIB_RG3GAINY = 3. DN
Info	03/07/24	00:29:06.447	CSTOL	0	1	MAG_HSK_SID15 ICV_FIB_RG3GAINZ = 3. DN
Info	03/07/24	00:29:06.543	CSTOL	0	1	MAG_HSK_PW MAGORANGE = RANGE1
Info	03/07/24	00:29:06.555	CSTOL	0	1	MAG_HSK_PW MAGIRANGE = RANGE2
Info	03/07/24	00:29:06.588	CSTOL	0	1	@PW  Range change completed successfully.
Info	03/07/24	00:39:07.494	CSTOL	0	1	@PW  Starting procedure $RCSfile: mag_change_range.prc,v $
Info	03/07/24	00:39:07.506	CSTOL	0	1	@PW  $Revision: 1.0 $
Info	03/07/24	00:39:07.585	CSTOL	0	1	@PW  Disabling ICU autorange for FIB...
Info	03/07/24	00:39:11.776	CSTOL	0	1	@PW  Disable FIB ICU autorange command completed.
Info	03/07/24	00:39:11.871	CSTOL	0	1	@PW  Disabling FEE autorange for FIB...
Info	03/07/24	00:39:15.776	CSTOL	0	1	@PW  Disable FIB FEE autorange command completed.
Info	03/07/24	00:39:15.823	CSTOL	0	1	@PW  Commanding FIB MAG into RANGE1
Info	03/07/24	00:39:15.835	CSTOL	0	1	@PW  with all Gains set to 3...
Info	03/07/24	00:39:19.775	CSTOL	0	1	@PW  Command FIB into RANGE1 completed.
Info	03/07/24	00:39:19.865	CSTOL	0	1	@PW  Re-enabling FEE autorange for FIB with AR delay S50...
Info	03/07/24	00:39:23.775	CSTOL	0	1	@PW  Re-enable FIB FEE autorange command completed.
Info	03/07/24	00:39:27.789	CSTOL	0	1	@PW  Power packet received. Proceeding to verification.
Info	03/07/24	00:39:32.229	CSTOL	0	1	@PW  SID15 packet received. Proceeding to verification.
Info	03/07/24	00:39:32.253	CSTOL	0	1	MAG_HSK_SID15 ICV_FIB_RG0GAINX = 3. DN
Info	03/07/24	00:39:32.266	CSTOL	0	1	MAG_HSK_SID15 ICV_FIB_RG0GAINY = 3. DN
Info	03/07/24	00:39:32.276	CSTOL	0	1	MAG_HSK_SID15 ICV_FIB_RG0GAINZ = 3. DN
Info	03/07/24	00:39:32.289	CSTOL	0	1	MAG_HSK_SID15 ICV_FIB_RG1GAINX = 3. DN
Info	03/07/24	00:39:32.301	CSTOL	0	1	MAG_HSK_SID15 ICV_FIB_RG1GAINY = 3. DN
Info	03/07/24	00:39:32.313	CSTOL	0	1	MAG_HSK_SID15 ICV_FIB_RG1GAINZ = 3. DN
Info	03/07/24	00:39:32.325	CSTOL	0	1	MAG_HSK_SID15 ICV_FIB_RG2GAINX = 3. DN
Info	03/07/24	00:39:32.336	CSTOL	0	1	MAG_HSK_SID15 ICV_FIB_RG2GAINY = 3. DN
Info	03/07/24	00:39:32.354	CSTOL	0	1	MAG_HSK_SID15 ICV_FIB_RG2GAINZ = 3. DN
Info	03/07/24	00:39:32.365	CSTOL	0	1	MAG_HSK_SID15 ICV_FIB_RG3GAINX = 3. DN
Info	03/07/24	00:39:32.377	CSTOL	0	1	MAG_HSK_SID15 ICV_FIB_RG3GAINY = 3. DN
Info	03/07/24	00:39:32.388	CSTOL	0	1	MAG_HSK_SID15 ICV_FIB_RG3GAINZ = 3. DN
Info	03/07/24	00:39:32.654	CSTOL	0	1	MAG_HSK_PW MAGORANGE = RANGE1
Info	03/07/24	00:39:32.664	CSTOL	0	1	MAG_HSK_PW MAGIRANGE = RANGE1
Info	03/07/24	00:39:32.703	CSTOL	0	1	@PW  Range change completed successfully.
Info	03/07/24	00:39:36.653	CSTOL	0	1	@PW  Status packet received. Proceeding to verification.
Info	03/07/24	00:39:36.766	CSTOL	0	1	MAG_HSK_STATUS MAGMODE = Burst
Info	03/07/24	00:39:36.816	CSTOL	0	1	@PW  MAG autoranging correctly configured.
Info	03/07/24	00:49:38.210	CSTOL	0	1	@PW  Starting procedure $RCSfile: mag_change_range.prc,v $
Info	03/07/24	00:49:38.229	CSTOL	0	1	@PW  $Revision: 1.0 $
Info	03/07/24	00:49:38.303	CSTOL	0	1	@PW  Disabling ICU autorange for FOB...
Info	03/07/24	00:49:41.713	CSTOL	0	1	@PW  Disable FOB ICU autorange command completed.
Info	03/07/24	00:49:41.802	CSTOL	0	1	@PW  Disabling FEE autorange for FOB...
Info	03/07/24	00:49:45.704	CSTOL	0	1	@PW  Disable FOB FEE autorange command completed.
Info	03/07/24	00:49:45.750	CSTOL	0	1	@PW  Commanding FOB MAG into RANGE0
Info	03/07/24	00:49:45.763	CSTOL	0	1	@PW  with all Gains set to 3...
Info	03/07/24	00:49:49.717	CSTOL	0	1	@PW  Command FOB into RANGE0 completed.
Info	03/07/24	00:49:49.812	CSTOL	0	1	@PW  Re-enabling FEE autorange for FOB with AR delay S50...
Info	03/07/24	00:49:53.707	CSTOL	0	1	@PW  Re-enable FOB FEE autorange command completed.
Info	03/07/24	00:49:57.713	CSTOL	0	1	@PW  Power packet received. Proceeding to verification.
Info	03/07/24	00:50:02.177	CSTOL	0	1	@PW  SID15 packet received. Proceeding to verification.
Info	03/07/24	00:50:02.200	CSTOL	0	1	MAG_HSK_SID15 ICV_FIB_RG0GAINX = 3. DN
Info	03/07/24	00:50:02.213	CSTOL	0	1	MAG_HSK_SID15 ICV_FIB_RG0GAINY = 3. DN
Info	03/07/24	00:50:02.229	CSTOL	0	1	MAG_HSK_SID15 ICV_FIB_RG0GAINZ = 3. DN
Info	03/07/24	00:50:02.240	CSTOL	0	1	MAG_HSK_SID15 ICV_FIB_RG1GAINX = 3. DN
Info	03/07/24	00:50:02.250	CSTOL	0	1	MAG_HSK_SID15 ICV_FIB_RG1GAINY = 3. DN
Info	03/07/24	00:50:02.263	CSTOL	0	1	MAG_HSK_SID15 ICV_FIB_RG1GAINZ = 3. DN
Info	03/07/24	00:50:02.275	CSTOL	0	1	MAG_HSK_SID15 ICV_FIB_RG2GAINX = 3. DN
Info	03/07/24	00:50:02.292	CSTOL	0	1	MAG_HSK_SID15 ICV_FIB_RG2GAINY = 3. DN
Info	03/07/24	00:50:02.303	CSTOL	0	1	MAG_HSK_SID15 ICV_FIB_RG2GAINZ = 3. DN
Info	03/07/24	00:50:02.315	CSTOL	0	1	MAG_HSK_SID15 ICV_FIB_RG3GAINX = 3. DN
Info	03/07/24	00:50:02.326	CSTOL	0	1	MAG_HSK_SID15 ICV_FIB_RG3GAINY = 3. DN
Info	03/07/24	00:50:02.336	CSTOL	0	1	MAG_HSK_SID15 ICV_FIB_RG3GAINZ = 3. DN
Info	03/07/24	00:50:02.437	CSTOL	0	1	MAG_HSK_PW MAGORANGE = RANGE0
Info	03/07/24	00:50:02.450	CSTOL	0	1	MAG_HSK_PW MAGIRANGE = RANGE1
Info	03/07/24	00:50:02.489	CSTOL	0	1	@PW  Range change completed successfully.
Info	03/07/24	01:00:03.970	CSTOL	0	1	@PW  Starting procedure $RCSfile: mag_change_range.prc,v $
Info	03/07/24	01:00:03.982	CSTOL	0	1	@PW  $Revision: 1.0 $
Info	03/07/24	01:00:04.059	CSTOL	0	1	@PW  Disabling ICU autorange for FIB...
Info	03/07/24	01:00:07.691	CSTOL	0	1	@PW  Disable FIB ICU autorange command completed.
Info	03/07/24	01:00:07.776	CSTOL	0	1	@PW  Disabling FEE autorange for FIB...
Info	03/07/24	01:00:11.697	CSTOL	0	1	@PW  Disable FIB FEE autorange command completed.
Info	03/07/24	01:00:11.746	CSTOL	0	1	@PW  Commanding FIB MAG into RANGE0
Info	03/07/24	01:00:11.759	CSTOL	0	1	@PW  with all Gains set to 3...
Info	03/07/24	01:00:15.694	CSTOL	0	1	@PW  Command FIB into RANGE0 completed.
Info	03/07/24	01:00:15.788	CSTOL	0	1	@PW  Re-enabling FEE autorange for FIB with AR delay S50...
Info	03/07/24	01:00:19.690	CSTOL	0	1	@PW  Re-enable FIB FEE autorange command completed.
Info	03/07/24	01:00:23.690	CSTOL	0	1	@PW  Power packet received. Proceeding to verification.
Info	03/07/24	01:00:28.085	CSTOL	0	1	@PW  SID15 packet received. Proceeding to verification.
Info	03/07/24	01:00:28.108	CSTOL	0	1	MAG_HSK_SID15 ICV_FIB_RG0GAINX = 3. DN
Info	03/07/24	01:00:28.119	CSTOL	0	1	MAG_HSK_SID15 ICV_FIB_RG0GAINY = 3. DN
Info	03/07/24	01:00:28.131	CSTOL	0	1	MAG_HSK_SID15 ICV_FIB_RG0GAINZ = 3. DN
Info	03/07/24	01:00:28.150	CSTOL	0	1	MAG_HSK_SID15 ICV_FIB_RG1GAINX = 3. DN
Info	03/07/24	01:00:28.161	CSTOL	0	1	MAG_HSK_SID15 ICV_FIB_RG1GAINY = 3. DN
Info	03/07/24	01:00:28.171	CSTOL	0	1	MAG_HSK_SID15 ICV_FIB_RG1GAINZ = 3. DN
Info	03/07/24	01:00:28.184	CSTOL	0	1	MAG_HSK_SID15 ICV_FIB_RG2GAINX = 3. DN
Info	03/07/24	01:00:28.194	CSTOL	0	1	MAG_HSK_SID15 ICV_FIB_RG2GAINY = 3. DN
Info	03/07/24	01:00:28.204	CSTOL	0	1	MAG_HSK_SID15 ICV_FIB_RG2GAINZ = 3. DN
Info	03/07/24	01:00:28.219	CSTOL	0	1	MAG_HSK_SID15 ICV_FIB_RG3GAINX = 3. DN
Info	03/07/24	01:00:28.233	CSTOL	0	1	MAG_HSK_SID15 ICV_FIB_RG3GAINY = 3. DN
Info	03/07/24	01:00:28.244	CSTOL	0	1	MAG_HSK_SID15 ICV_FIB_RG3GAINZ = 3. DN
Info	03/07/24	01:00:28.357	CSTOL	0	1	MAG_HSK_PW MAGORANGE = RANGE0
Info	03/07/24	01:00:28.368	CSTOL	0	1	MAG_HSK_PW MAGIRANGE = RANGE0
Info	03/07/24	01:00:28.401	CSTOL	0	1	@PW  Range change completed successfully.
Info	03/07/24	01:00:31.696	CSTOL	0	1	@PW  Status packet received. Proceeding to verification.
Info	03/07/24	01:00:31.819	CSTOL	0	1	MAG_HSK_STATUS MAGMODE = Burst
Info	03/07/24	01:00:31.868	CSTOL	0	1	@PW  MAG autoranging correctly configured.
Info	03/07/24	01:10:33.075	CSTOL	0	1	@PW  Starting procedure $RCSfile: mag_mode_change.prc,v $
Info	03/07/24	01:10:33.085	CSTOL	0	1	@PW  $Revision: 1.0 $
Info	03/07/24	01:10:36.559	CSTOL	0	1	@PW Config Mode transition event received.
Info	03/07/24	01:10:36.602	CSTOL	0	1	MAG_PROG_MTRAN EVENT_ID = modeTransition
Info	03/07/24	01:10:36.614	CSTOL	0	1	MAG_PROG_MTRAN PREVM_ID = Burst
Info	03/07/24	01:10:36.634	CSTOL	0	1	MAG_PROG_MTRAN CURRM_ID = Config
Info	03/07/24	01:10:37.332	CSTOL	0	1	@PW  Starting procedure $RCSfile: mag_set_filter.prc,v $
Info	03/07/24	01:10:37.345	CSTOL	0	1	@PW  $Revision: 1.0 $
Info	03/07/24	01:10:37.408	CSTOL	0	1	@PW  Setting Outboard Burst to NOFILTER...
Info	03/07/24	01:10:40.555	CSTOL	0	1	@PW  Command to set Outboard Burst filter to NOFILTER completed.
Info	03/07/24	01:10:40.627	CSTOL	0	1	@PW  Setting Outboard Normal to NOFILTER...
Info	03/07/24	01:10:44.555	CSTOL	0	1	@PW  Command to set Outboard Normal filter to NOFILTER completed.
Info	03/07/24	01:10:44.634	CSTOL	0	1	@PW  Setting Inboard Burst to NOFILTER...
Info	03/07/24	01:10:48.555	CSTOL	0	1	@PW  Command to set Inboard Burst filter to NOFILTER completed.
Info	03/07/24	01:10:48.634	CSTOL	0	1	@PW  Setting Inboard Normal to NOFILTER...
Info	03/07/24	01:10:52.555	CSTOL	0	1	@PW  Command to set Inboard Normal filter to NOFILTER completed. Proceeding to verification...
Info	03/07/24	01:10:56.674	CSTOL	0	1	@PW  SID15 packet received. Proceeding to verification.
Info	03/07/24	01:10:56.760	CSTOL	0	1	@PW  New MAG filter settings:
Info	03/07/24	01:10:56.773	CSTOL	0	1	MAG_HSK_SID15 ICV_FILTTYPE_IBSB = NOFILTER
Info	03/07/24	01:10:56.785	CSTOL	0	1	MAG_HSK_SID15 ICV_FILTTYPE_IBSN = NOFILTER
Info	03/07/24	01:10:56.796	CSTOL	0	1	MAG_HSK_SID15 ICV_FILTTYPE_OBSN = NOFILTER
Info	03/07/24	01:10:56.808	CSTOL	0	1	MAG_HSK_SID15 ICV_FILTTYPE_OBSB = NOFILTER
Info	03/07/24	01:10:56.845	CSTOL	0	1	@PW  MAG Science filters checked successfully with SID15.
Info	03/07/24	01:10:56.956	CSTOL	0	1	@PW  Performing a vector bit shift of 5...
Info	03/07/24	01:11:00.558	CSTOL	0	1	@PW  Bit shift command completed. Proceeding to verification...
Info	03/07/24	01:11:04.677	CSTOL	0	1	@PW  SID15 packet received. Proceeding to verification.
Info	03/07/24	01:11:04.697	CSTOL	0	1	MAG_HSK_SID15 ICV_VECBITSHFT = 5. DN
Info	03/07/24	01:11:04.752	CSTOL	0	1	@PW  MAG bit shift value confirmed.
Info	03/07/24	01:11:04.803	CSTOL	0	1	@PW  Sending command to go to Burst 128-128 mode...
Info	03/07/24	01:11:04.831	CSTOL	0	1	@PW  Sending command to go to Burst 128-128 mode for 1200 seconds...
Info	03/07/24	01:11:05.526	CSTOL	0	1	@PW  Starting procedure $RCSfile: mag_science.prc,v $
Info	03/07/24	01:11:05.539	CSTOL	0	1	@PW  $Revision: 1.0 $
Info	03/07/24	01:11:09.572	CSTOL	0	1	@PW Burst Mode transition event received. Proceeding to verification.
Info	03/07/24	01:11:09.618	CSTOL	0	1	MAG_PROG_MTRAN EVENT_ID = modeTransition
Info	03/07/24	01:11:09.630	CSTOL	0	1	MAG_PROG_MTRAN PREVM_ID = Config
Info	03/07/24	01:11:09.648	CSTOL	0	1	MAG_PROG_MTRAN CURRM_ID = Burst
Info	03/07/24	01:11:09.680	CSTOL	0	1	@PW  MAG successfully changed mode to Burst
Info	03/07/24	01:11:10.414	CSTOL	0	1	@PW  Starting procedure $RCSfile: mag_verif_science.prc,v $
Info	03/07/24	01:11:10.424	CSTOL	0	1	@PW  $Revision: 1.0 $
Info	03/07/24	01:11:10.446	CSTOL	0	1	@PW  Verifying FEE configuration...
Info	03/07/24	01:11:11.599	CSTOL	0	1	@PW  Power packet received. Proceeding to verification.
Info	03/07/24	01:11:15.598	CSTOL	0	1	@PW  Status packet received. Proceeding to verification.
Info	03/07/24	01:11:20.078	CSTOL	0	1	@PW  SID15 packet received. Proceeding to verification.
Info	03/07/24	01:11:20.288	CSTOL	0	1	MAG_HSK_PW MAGORANGE = RANGE0
Info	03/07/24	01:11:20.298	CSTOL	0	1	MAG_HSK_PW MAGIRANGE = RANGE0
Info	03/07/24	01:11:20.309	CSTOL	0	1	MAG_HSK_STATUS FOBSTAT = Active
Info	03/07/24	01:11:20.319	CSTOL	0	1	MAG_HSK_STATUS FIBSTAT = Active
Info	03/07/24	01:11:20.332	CSTOL	0	1	MAG_HSK_STATUS FOBAR = Enabled
Info	03/07/24	01:11:20.344	CSTOL	0	1	MAG_HSK_STATUS FIBAR = Enabled
Info	03/07/24	01:11:20.355	CSTOL	0	1	MAG_HSK_STATUS ICUFOBAR = Disabled
Info	03/07/24	01:11:20.368	CSTOL	0	1	MAG_HSK_STATUS ICUFIBAR = Disabled
Info	03/07/24	01:11:20.381	CSTOL	0	1	@PW  Number of failed tries for FEE activation:
Info	03/07/24	01:11:20.391	CSTOL	0	1	MAG_HSK_SID15 ISV_FOB_ACTTRIES = 1. DN
Info	03/07/24	01:11:20.404	CSTOL	0	1	MAG_HSK_SID15 ISV_FIB_ACTTRIES = 1. DN
Info	03/07/24	01:11:20.447	CSTOL	0	1	@PW  FEEs are active and in a safe configuration. Proceeding to science verification.
Info	03/07/24	01:11:24.572	CSTOL	0	1	@PW  Science snapshot HK packet received. Proceeding to verification.
Info	03/07/24	01:11:24.697	CSTOL	0	1	MAG_HSK_SCI BPRI_OUTRATE = HZ_128
Info	03/07/24	01:11:24.709	CSTOL	0	1	MAG_HSK_SCI BSEC_OUTRATE = HZ_128
Info	03/07/24	01:11:24.720	CSTOL	0	1	MAG_HSK_SID15 ICV_OUTRATE_OBSN = HZ_2
Info	03/07/24	01:11:24.733	CSTOL	0	1	MAG_HSK_SID15 ICV_OUTRATE_IBSN = HZ_2
Info	03/07/24	01:11:24.746	CSTOL	0	1	MAG_HSK_SID15 ICV_OUTRATE_OBSB = HZ_128
Info	03/07/24	01:11:24.760	CSTOL	0	1	MAG_HSK_SID15 ICV_OUTRATE_IBSB = HZ_128
Info	03/07/24	01:11:24.782	CSTOL	0	1	MAG_HSK_PW MAGORANGE = RANGE0
Info	03/07/24	01:11:24.795	CSTOL	0	1	MAG_HSK_PW MAGIRANGE = RANGE0
Info	03/07/24	01:11:24.825	CSTOL	0	1	@PW  MAG generating science and FEEs correctly configured.
Info	03/07/24	01:11:25.490	CSTOL	0	1	@PW  Starting procedure $RCSfile: mag_ramp.prc,v $
Info	03/07/24	01:11:25.502	CSTOL	0	1	@PW  $Revision: 1.0 $
Info	03/07/24	01:11:25.525	CSTOL	0	1	@PW  Enabling FOB ramp...
Info	03/07/24	01:11:29.641	CSTOL	0	1	@PW  MAG FOB ramp enable command completed.
Info	03/07/24	01:11:30.582	CSTOL	0	1	@PW  Starting procedure $RCSfile: mag_ramp.prc,v $
Info	03/07/24	01:11:30.594	CSTOL	0	1	@PW  $Revision: 1.0 $
Info	03/07/24	01:11:30.618	CSTOL	0	1	@PW  Enabling FIB ramp...
Info	03/07/24	01:11:34.510	CSTOL	0	1	@PW  MAG FIB ramp enable command completed.
Info	03/07/24	01:16:35.938	CSTOL	0	1	@PW  Starting procedure $RCSfile: mag_change_range.prc,v $
Info	03/07/24	01:16:35.951	CSTOL	0	1	@PW  $Revision: 1.0 $
Info	03/07/24	01:16:36.032	CSTOL	0	1	@PW  Disabling ICU autorange for FOB...
Info	03/07/24	01:16:39.588	CSTOL	0	1	@PW  Disable FOB ICU autorange command completed.
Info	03/07/24	01:16:39.686	CSTOL	0	1	@PW  Disabling FEE autorange for FOB...
Info	03/07/24	01:16:43.588	CSTOL	0	1	@PW  Disable FOB FEE autorange command completed.
Info	03/07/24	01:16:43.637	CSTOL	0	1	@PW  Commanding FOB MAG into RANGE0
Info	03/07/24	01:16:43.648	CSTOL	0	1	@PW  with all Gains set to 3...
Info	03/07/24	01:16:47.586	CSTOL	0	1	@PW  Command FOB into RANGE0 completed.
Info	03/07/24	01:16:47.680	CSTOL	0	1	@PW  Re-enabling FEE autorange for FOB with AR delay S50...
Info	03/07/24	01:16:51.594	CSTOL	0	1	@PW  Re-enable FOB FEE autorange command completed.
Info	03/07/24	01:16:55.581	CSTOL	0	1	@PW  Power packet received. Proceeding to verification.
Info	03/07/24	01:17:00.052	CSTOL	0	1	@PW  SID15 packet received. Proceeding to verification.
Info	03/07/24	01:17:00.073	CSTOL	0	1	MAG_HSK_SID15 ICV_FIB_RG0GAINX = 3. DN
Info	03/07/24	01:17:00.085	CSTOL	0	1	MAG_HSK_SID15 ICV_FIB_RG0GAINY = 3. DN
Info	03/07/24	01:17:00.102	CSTOL	0	1	MAG_HSK_SID15 ICV_FIB_RG0GAINZ = 3. DN
Info	03/07/24	01:17:00.114	CSTOL	0	1	MAG_HSK_SID15 ICV_FIB_RG1GAINX = 3. DN
Info	03/07/24	01:17:00.150	CSTOL	0	1	MAG_HSK_SID15 ICV_FIB_RG1GAINY = 3. DN
Info	03/07/24	01:17:00.177	CSTOL	0	1	MAG_HSK_SID15 ICV_FIB_RG1GAINZ = 3. DN
Info	03/07/24	01:17:00.187	CSTOL	0	1	MAG_HSK_SID15 ICV_FIB_RG2GAINX = 3. DN
Info	03/07/24	01:17:00.200	CSTOL	0	1	MAG_HSK_SID15 ICV_FIB_RG2GAINY = 3. DN
Info	03/07/24	01:17:00.213	CSTOL	0	1	MAG_HSK_SID15 ICV_FIB_RG2GAINZ = 3. DN
Info	03/07/24	01:17:00.232	CSTOL	0	1	MAG_HSK_SID15 ICV_FIB_RG3GAINX = 3. DN
Info	03/07/24	01:17:00.243	CSTOL	0	1	MAG_HSK_SID15 ICV_FIB_RG3GAINY = 3. DN
Info	03/07/24	01:17:00.256	CSTOL	0	1	MAG_HSK_SID15 ICV_FIB_RG3GAINZ = 3. DN
Info	03/07/24	01:17:00.354	CSTOL	0	1	MAG_HSK_PW MAGORANGE = RANGE0
Info	03/07/24	01:17:00.365	CSTOL	0	1	MAG_HSK_PW MAGIRANGE = RANGE0
Info	03/07/24	01:17:00.398	CSTOL	0	1	@PW  Range change completed successfully.
Info	03/07/24	01:17:01.071	CSTOL	0	1	@PW  Starting procedure $RCSfile: mag_change_range.prc,v $
Info	03/07/24	01:17:01.082	CSTOL	0	1	@PW  $Revision: 1.0 $
Info	03/07/24	01:17:01.154	CSTOL	0	1	@PW  Disabling ICU autorange for FIB...
Info	03/07/24	01:17:04.486	CSTOL	0	1	@PW  Disable FIB ICU autorange command completed.
Info	03/07/24	01:17:04.572	CSTOL	0	1	@PW  Disabling FEE autorange for FIB...
Info	03/07/24	01:17:08.476	CSTOL	0	1	@PW  Disable FIB FEE autorange command completed.
Info	03/07/24	01:17:08.519	CSTOL	0	1	@PW  Commanding FIB MAG into RANGE0
Info	03/07/24	01:17:08.530	CSTOL	0	1	@PW  with all Gains set to 3...
Info	03/07/24	01:17:12.480	CSTOL	0	1	@PW  Command FIB into RANGE0 completed.
Info	03/07/24	01:17:12.572	CSTOL	0	1	@PW  Re-enabling FEE autorange for FIB with AR delay S50...
Info	03/07/24	01:17:16.480	CSTOL	0	1	@PW  Re-enable FIB FEE autorange command completed.
Info	03/07/24	01:17:20.494	CSTOL	0	1	@PW  Power packet received. Proceeding to verification.
Info	03/07/24	01:17:24.677	CSTOL	0	1	@PW  SID15 packet received. Proceeding to verification.
Info	03/07/24	01:17:24.698	CSTOL	0	1	MAG_HSK_SID15 ICV_FIB_RG0GAINX = 3. DN
Info	03/07/24	01:17:24.710	CSTOL	0	1	MAG_HSK_SID15 ICV_FIB_RG0GAINY = 3. DN
Info	03/07/24	01:17:24.721	CSTOL	0	1	MAG_HSK_SID15 ICV_FIB_RG0GAINZ = 3. DN
Info	03/07/24	01:17:24.733	CSTOL	0	1	MAG_HSK_SID15 ICV_FIB_RG1GAINX = 3. DN
Info	03/07/24	01:17:24.744	CSTOL	0	1	MAG_HSK_SID15 ICV_FIB_RG1GAINY = 3. DN
Info	03/07/24	01:17:24.760	CSTOL	0	1	MAG_HSK_SID15 ICV_FIB_RG1GAINZ = 3. DN
Info	03/07/24	01:17:24.773	CSTOL	0	1	MAG_HSK_SID15 ICV_FIB_RG2GAINX = 3. DN
Info	03/07/24	01:17:24.783	CSTOL	0	1	MAG_HSK_SID15 ICV_FIB_RG2GAINY = 3. DN
Info	03/07/24	01:17:24.796	CSTOL	0	1	MAG_HSK_SID15 ICV_FIB_RG2GAINZ = 3. DN
Info	03/07/24	01:17:24.806	CSTOL	0	1	MAG_HSK_SID15 ICV_FIB_RG3GAINX = 3. DN
Info	03/07/24	01:17:24.822	CSTOL	0	1	MAG_HSK_SID15 ICV_FIB_RG3GAINY = 3. DN
Info	03/07/24	01:17:24.835	CSTOL	0	1	MAG_HSK_SID15 ICV_FIB_RG3GAINZ = 3. DN
Info	03/07/24	01:17:24.947	CSTOL	0	1	MAG_HSK_PW MAGORANGE = RANGE0
Info	03/07/24	01:17:24.959	CSTOL	0	1	MAG_HSK_PW MAGIRANGE = RANGE0
Info	03/07/24	01:17:24.990	CSTOL	0	1	@PW  Range change completed successfully.
Info	03/07/24	01:17:25.661	CSTOL	0	1	@PW  Starting procedure $RCSfile: mag_mode_change.prc,v $
Info	03/07/24	01:17:25.674	CSTOL	0	1	@PW  $Revision: 1.0 $
Info	03/07/24	01:17:29.500	CSTOL	0	1	@PW Config Mode transition event received.
Info	03/07/24	01:17:29.549	CSTOL	0	1	MAG_PROG_MTRAN EVENT_ID = modeTransition
Info	03/07/24	01:17:29.562	CSTOL	0	1	MAG_PROG_MTRAN PREVM_ID = Burst
Info	03/07/24	01:17:29.572	CSTOL	0	1	MAG_PROG_MTRAN CURRM_ID = Config
Info	03/07/24	01:17:30.244	CSTOL	0	1	@PW  Starting procedure $RCSfile: mag_set_filter.prc,v $
Info	03/07/24	01:17:30.256	CSTOL	0	1	@PW  $Revision: 1.0 $
Info	03/07/24	01:17:30.319	CSTOL	0	1	@PW  Setting Outboard Burst to CIC2NDORDER...
Info	03/07/24	01:17:33.496	CSTOL	0	1	@PW  Command to set Outboard Burst filter to CIC2NDORDER completed.
Info	03/07/24	01:17:33.569	CSTOL	0	1	@PW  Setting Outboard Normal to CIC2NDORDER...
Info	03/07/24	01:17:37.496	CSTOL	0	1	@PW  Command to set Outboard Normal filter to CIC2NDORDER completed.
Info	03/07/24	01:17:37.565	CSTOL	0	1	@PW  Setting Inboard Burst to CIC2NDORDER...
Info	03/07/24	01:17:41.494	CSTOL	0	1	@PW  Command to set Inboard Burst filter to CIC2NDORDER completed.
Info	03/07/24	01:17:41.559	CSTOL	0	1	@PW  Setting Inboard Normal to CIC2NDORDER...
Info	03/07/24	01:17:45.493	CSTOL	0	1	@PW  Command to set Inboard Normal filter to CIC2NDORDER completed. Proceeding to verification...
Info	03/07/24	01:17:49.691	CSTOL	0	1	@PW  SID15 packet received. Proceeding to verification.
Info	03/07/24	01:17:49.788	CSTOL	0	1	@PW  New MAG filter settings:
Info	03/07/24	01:17:49.799	CSTOL	0	1	MAG_HSK_SID15 ICV_FILTTYPE_IBSB = CIC2NDORDER
Info	03/07/24	01:17:49.811	CSTOL	0	1	MAG_HSK_SID15 ICV_FILTTYPE_IBSN = CIC2NDORDER
Info	03/07/24	01:17:49.822	CSTOL	0	1	MAG_HSK_SID15 ICV_FILTTYPE_OBSN = CIC2NDORDER
Info	03/07/24	01:17:49.838	CSTOL	0	1	MAG_HSK_SID15 ICV_FILTTYPE_OBSB = CIC2NDORDER
Info	03/07/24	01:17:49.871	CSTOL	0	1	@PW  MAG Science filters checked successfully with SID15.
Info	03/07/24	01:17:49.974	CSTOL	0	1	@PW  Performing a vector bit shift of 0...
Info	03/07/24	01:17:53.496	CSTOL	0	1	@PW  Bit shift command completed. Proceeding to verification...
Info	03/07/24	01:17:57.693	CSTOL	0	1	@PW  SID15 packet received. Proceeding to verification.
Info	03/07/24	01:17:57.716	CSTOL	0	1	MAG_HSK_SID15 ICV_VECBITSHFT = 0. DN
Info	03/07/24	01:17:57.773	CSTOL	0	1	@PW  MAG bit shift value confirmed.
Info	03/07/24	01:17:57.815	CSTOL	0	1	@PW  Sending command to go to Normal 2-2 science mode...
Info	03/07/24	01:17:58.523	CSTOL	0	1	@PW  Starting procedure $RCSfile: mag_science.prc,v $
Info	03/07/24	01:17:58.542	CSTOL	0	1	@PW  $Revision: 1.0 $
Info	03/07/24	01:18:02.522	CSTOL	0	1	@PW Normal Mode transition event received. Proceeding to verification.
Info	03/07/24	01:18:02.571	CSTOL	0	1	MAG_PROG_MTRAN EVENT_ID = modeTransition
Info	03/07/24	01:18:02.582	CSTOL	0	1	MAG_PROG_MTRAN PREVM_ID = Config
Info	03/07/24	01:18:02.592	CSTOL	0	1	MAG_PROG_MTRAN CURRM_ID = Normal
Info	03/07/24	01:18:02.627	CSTOL	0	1	@PW  MAG successfully changed mode to Normal
Info	03/07/24	01:18:03.362	CSTOL	0	1	@PW  Starting procedure $RCSfile: mag_verif_science.prc,v $
Info	03/07/24	01:18:03.374	CSTOL	0	1	@PW  $Revision: 1.0 $
Info	03/07/24	01:18:03.397	CSTOL	0	1	@PW  Verifying FEE configuration...
Info	03/07/24	01:18:07.536	CSTOL	0	1	@PW  Power packet received. Proceeding to verification.
Info	03/07/24	01:18:11.542	CSTOL	0	1	@PW  Status packet received. Proceeding to verification.
Info	03/07/24	01:18:15.657	CSTOL	0	1	@PW  SID15 packet received. Proceeding to verification.
Info	03/07/24	01:18:15.842	CSTOL	0	1	MAG_HSK_PW MAGORANGE = RANGE0
Info	03/07/24	01:18:15.851	CSTOL	0	1	MAG_HSK_PW MAGIRANGE = RANGE0
Info	03/07/24	01:18:15.868	CSTOL	0	1	MAG_HSK_STATUS FOBSTAT = Active
Info	03/07/24	01:18:15.878	CSTOL	0	1	MAG_HSK_STATUS FIBSTAT = Active
Info	03/07/24	01:18:15.890	CSTOL	0	1	MAG_HSK_STATUS FOBAR = Enabled
Info	03/07/24	01:18:15.901	CSTOL	0	1	MAG_HSK_STATUS FIBAR = Enabled
Info	03/07/24	01:18:15.913	CSTOL	0	1	MAG_HSK_STATUS ICUFOBAR = Disabled
Info	03/07/24	01:18:15.924	CSTOL	0	1	MAG_HSK_STATUS ICUFIBAR = Disabled
Info	03/07/24	01:18:15.944	CSTOL	0	1	@PW  Number of failed tries for FEE activation:
Info	03/07/24	01:18:15.954	CSTOL	0	1	MAG_HSK_SID15 ISV_FOB_ACTTRIES = 1. DN
Info	03/07/24	01:18:15.967	CSTOL	0	1	MAG_HSK_SID15 ISV_FIB_ACTTRIES = 1. DN
Info	03/07/24	01:18:16.005	CSTOL	0	1	@PW  FEEs are active and in a safe configuration. Proceeding to science verification.
Info	03/07/24	01:18:19.555	CSTOL	0	1	@PW  Science snapshot HK packet received. Proceeding to verification.
Info	03/07/24	01:18:19.684	CSTOL	0	1	MAG_HSK_SCI NPRI_OUTRATE = HZ_2
Info	03/07/24	01:18:19.696	CSTOL	0	1	MAG_HSK_SCI NSEC_OUTRATE = HZ_2
Info	03/07/24	01:18:19.707	CSTOL	0	1	MAG_HSK_SID15 ICV_OUTRATE_OBSN = HZ_2
Info	03/07/24	01:18:19.719	CSTOL	0	1	MAG_HSK_SID15 ICV_OUTRATE_IBSN = HZ_2
Info	03/07/24	01:18:19.730	CSTOL	0	1	MAG_HSK_SID15 ICV_OUTRATE_OBSB = HZ_128
Info	03/07/24	01:18:19.746	CSTOL	0	1	MAG_HSK_SID15 ICV_OUTRATE_IBSB = HZ_128
Info	03/07/24	01:18:19.769	CSTOL	0	1	MAG_HSK_PW MAGORANGE = RANGE0
Info	03/07/24	01:18:19.780	CSTOL	0	1	MAG_HSK_PW MAGIRANGE = RANGE0
Info	03/07/24	01:18:19.815	CSTOL	0	1	@PW  MAG generating science and FEEs correctly configured.
Info	03/07/24	01:18:20.028	CSTOL	0	1	@PW  Re-enabling ICU autorange for FOB with AR delay 38400...
Info	03/07/24	01:18:23.477	CSTOL	0	1	@PW  Enable FOB ICU autorange command completed.
Info	03/07/24	01:18:23.546	CSTOL	0	1	@PW  Re-enabling ICU autorange for FOB with AR delay 38400...
Info	03/07/24	01:18:27.467	CSTOL	0	1	@PW  Enable FIB ICU autorange command completed.
Info	03/07/24	01:18:31.539	CSTOL	0	1	@PW  Status packet received. Proceeding to verification.
Info	03/07/24	01:18:31.654	CSTOL	0	1	MAG_HSK_STATUS MAGMODE = Normal
Info	03/07/24	01:18:31.701	CSTOL	0	1	@PW  MAG autoranging correctly configured.
Info	03/07/24	01:18:31.733	CSTOL	0	1	@PW  Leaving MAG to collect data in Normal 2-2 science mode. Enter GO to go to commanded Safe.
Info	03/07/24	01:26:01.438	CSTOL	0	1	@PW  Starting procedure $RCSfile: mag_safe.prc,v $
Info	03/07/24	01:26:01.457	CSTOL	0	1	@PW  $Revision: 1.0 $
Info	03/07/24	01:26:01.500	CSTOL	0	1	@PW  Commanding MAG into Safe mode...
Info	03/07/24	01:26:02.092	CSTOL	0	1	@PW  Starting procedure $RCSfile: mag_mode_change.prc,v $
Info	03/07/24	01:26:02.105	CSTOL	0	1	@PW  $Revision: 1.0 $
Info	03/07/24	01:26:05.499	CSTOL	0	1	@PW Safe Mode transition event received.
Info	03/07/24	01:26:05.546	CSTOL	0	1	MAG_PROG_MTRAN EVENT_ID = modeTransition
Info	03/07/24	01:26:05.558	CSTOL	0	1	MAG_PROG_MTRAN PREVM_ID = Normal
Info	03/07/24	01:26:05.573	CSTOL	0	1	MAG_PROG_MTRAN CURRM_ID = Safe
Info	03/07/24	01:26:09.493	CSTOL	0	1	@PW  Status packet received. Proceeding to verification.
Info	03/07/24	01:26:09.581	CSTOL	0	1	MAG_HSK_STATUS FOBSTAT = Inactive
Info	03/07/24	01:26:09.592	CSTOL	0	1	MAG_HSK_STATUS FIBSTAT = Inactive
Info	03/07/24	01:26:09.604	CSTOL	0	1	MAG_HSK_STATUS MAGMODE = Safe
Info	03/07/24	01:26:09.637	CSTOL	0	1	@PW  Sensors have been deactivated, MAG in SAFE mode.
Info	03/07/24	01:26:10.303	CSTOL	0	1	@PW  Starting procedure $RCSfile: mag_pwr_off.prc,v $
Info	03/07/24	01:26:10.322	CSTOL	0	1	@PW  $Revision: 1.0 $
Info	03/07/24	01:26:10.345	CSTOL	0	1	@PW  Call out to FC to power down MAG and confirm MAG is OFF.
Info	03/07/24	01:26:13.582	CSTOL	0	1	@PW  MAG power down confirmed.
Info	03/07/24	01:26:13.657	CSTOL	0	1	@PW  MAG instrument Comprehensive Performance Test complete.
Info	03/07/24	01:26:13.668	CSTOL	0	1	@PW  FC GO to FINISH.
Info	03/07/24	01:26:18.167	CSTOL	0	1	@PW  End of MAG Comprehensive Performance Test.
Info	03/07/24	01:26:18.180	CSTOL	0	1	@PW  This MAG CPT combined with post-processing of the science
Info	03/07/24	01:26:18.196	CSTOL	0	1	@PW  and HK data verifies the folling requirements:
Info	03/07/24	01:26:18.207	CSTOL	0	1	@PW  RMAG-1049, RMAG-1071, RMAG-1073, RMAG-1074, RMAG-1116, RMAG-1534
Info	03/07/24	01:26:18.217	CSTOL	0	1	@PW  RMAG-1118, RMAG-1119
Info	03/07/24	01:26:18.229	CSTOL	0	1	@PW  Finishing $RCSfile: mag_cpt.prc,v $
Error	03/07/24	01:27:11.848	OKBios	0	1	Connection to Opal Kelly device terminated.
